Add test coverage for pending EP
department-of-veterans-affairs/vets-api pull request #10533
Opened 2022-08-22 23:30 UTC by allthesignals

Adds a test for a scenario in which there are pending EPs. Ensures it offramps and skips MAS calls.

Also, in the submit_form526 spec, restricts multiple EVSS calls for pending EPs.

## Description of change
Increases test coverage

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR

2022-08-23 13:53 UTC, yoomlam commented on spec/jobs/rapid_ready_for_decision/form526_base_job_spec.rb
> +              expect(MailAutomation::Client).not_to receive(:new)
To DRY the code, consider moving this line to the prior test and renaming the prior test `'off-ramps to the non-RRD process and does not notify MAS'`, and removing this test.

2022-08-23 13:53 UTC, yoomlam requested changes
1 suggestion

2022-09-14 20:09 UTC, LindseySaari approved these changes

2022-10-14 21:45 UTC, yoomlam commented
@nanotone Do we want this PR or can it be closed?

2022-10-17 16:00 UTC, nanotone commented
@yoomlam Yeah I'm not convinced more integration tests is the best path forward, at this point. I'm going to close it.

2022-10-17 16:00 UTC, closed without merging