Added new text base appeals error report
department-of-veterans-affairs/vets-api pull request #11076
Opened 2022-11-04 17:15 UTC by michelpmcdonald

## Description of change

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR

2022-11-08 21:17 UTC, holdenhinkle submitted a review, later dismissed

2022-11-08 22:15 UTC, cilestin requested changes
Just a small update and it should be good to go!

2022-11-08 22:15 UTC, cilestin commented on modules/appeals_api/app/mailers/appeals_api/weekly_error_report_mailer.rb
> +      body += stuck_err_hlrs
Since this is essentially a CSV, let's add a header line that details what each column is

2022-11-10 17:43 UTC, cilestin approved these changes

2022-11-10 17:44 UTC, merged