[22884] adds USiP logging to SiS auth & refactors applications constants
department-of-veterans-affairs/vets-api pull request #11345
Opened 2022-12-09 17:27 UTC by bramleyjl

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintainence of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2022-12-12 20:56 UTC, holdenhinkle submitted a review, later dismissed
LGTM 🤘

2022-12-13 20:04 UTC, bosawt commented
Tested by authenticating with `application=ebenefits`, confirmed the logs:
`SSO_NEW_KEY, tags: ["context:idme", "version:v1", "client_id:ebenefits"]`
`LOGIN_STATUS_SUCCESS, tags: ["context:idme", "version:v1", "client_id:ebenefits"]`

Also tested by authenticating with `application=nothing`, confirmed the logs:
`SSO_NEW_KEY, tags: ["context:idme", "version:v1", "client_id:nothing"]`
` LOGIN_STATUS_SUCCESS, tags: ["context:idme", "version:v1", "client_id:nothing"]`

2022-12-13 20:09 UTC, bosawt commented
The va.gov USIP calls backend without an application param, right? Wonder if we could set a default for this when `application` isn't defined, like `vaweb`. That way we'd be able to explicitly know the web calls, instead of assuming it happens when `client_id` is blank

2022-12-13 20:10 UTC, bosawt requested changes
Just had a small comment about setting a default, otherwise all looks good! 

I put in a separate comment but I tested as well and looks good

2022-12-13 20:46 UTC, bosawt commented on lib/saml/url_service.rb
> +    UNIFIED_SIGN_IN_CLIENTS = %w[mhv myvahealth ebenefits vamobile vaoccmobile].freeze
We also need to add `vaweb` here now, right?

2022-12-13 21:30 UTC, bosawt approved these changes
looks good!

2022-12-14 18:24 UTC, bosawt approved these changes
👍

2022-12-14 19:54 UTC, merged