Add Dockerfile for preview environment deploys
department-of-veterans-affairs/vets-api pull request #11757
Opened 2023-02-08 22:33 UTC by powellkerry

Add Dockerfile-pe for preview environments. Add command to clone vets-api-mockdata to that file. Copy and re-name import-va-certs.sh from k8s branch

## Summary

- Create a Dockerfile for use with building images to deploy for preview environments
- Dockerfile-pe is a copy of the Dockerfile on the k8s branch which will be modified to fulfill the requirements for preview environments. 
- Added a run command to clone `vets-api-mockdata`
- import-va-certs-pe.sh is a copy from the k8s branch and is used to import required certificates into the docker image. I added a TODO in this file to remove it and update references to it when the k8s branch is merged to master.
- My Team: Platform-Preview Environments (Team 4), this team will maintain these files.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#50568: https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/50568
- department-of-veterans-affairs/va.gov-team#52413: https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/52413

## Testing done

- This is a new Dockerfile and does not affect old behavior
- The new Dockerfile was ran locally and was successful
- Verified that `vets-api-mockdata` was successfully cloned at the root of the image file directory

## What areas of the site does it impact?
- This change does not affect existing functionality

## Acceptance criteria

- [ ] The docker image builds successfully
- [ ] Documentation has been updated: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2490761493/Vets-API+Docker+Image

This is a foundational commit, further work is scheduled to develop GitHub Actions to build this Dockerfile and to deploy it to AWS.

2023-02-09 16:17 UTC, CBonade submitted a review, later dismissed
Looks good to me given my extremely limited experience with writing dockerfiles

2023-02-10 15:46 UTC, rjohnson2011 approved these changes

2023-02-10 17:47 UTC, ericboehs commented on Dockerfile-pe
> +CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
Missing new line char.

2023-02-13 14:37 UTC, pjhill approved these changes
LGTM

2023-02-13 14:40 UTC, pjhill requested changes

2023-02-13 14:40 UTC, pjhill commented on Dockerfile-k8s
> +COPY ./import-va-certs-pe.sh .
Since we are de-duping this cert script this needs to change --

```suggestion
COPY ./import-va-certs-k8s.sh .
```

2023-02-13 14:40 UTC, pjhill commented on Dockerfile-k8s
> +RUN ./import-va-certs-pe.sh
```suggestion
RUN ./import-va-certs-k8s.sh
```

2023-02-13 20:33 UTC, pjhill submitted a review, later dismissed

2023-02-13 21:36 UTC, ericboehs commented on import-va-certs.sh
> +)
Missing new line char

2023-02-13 21:36 UTC, ericboehs approved these changes

2023-02-13 21:46 UTC, rjohnson2011 approved these changes

2023-02-13 22:01 UTC, merged