5086 verify military access in controller
department-of-veterans-affairs/vets-api pull request #12252
Opened 2023-03-24 19:50 UTC by cadibemma

## Summary

- The military information controller should confirm that the user can use the vet360 service

## Related issue(s)
- department-of-veterans-affairs/va-mobile-app#5086

## Testing done

- Added test for 403 response

## What areas of the site does it impact?
- None

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2023-03-24 20:04 UTC, aherzberg approved these changes
LGTM!

2023-03-24 20:18 UTC, kpethtel requested changes
I don't think you need to have this VCR because the outbound call is never made. I'd recommend removing the VCR you copied over because it's never actually used.

2023-03-24 20:42 UTC, kpethtel submitted a review, later dismissed

2023-03-24 20:42 UTC, kpethtel commented on modules/mobile/spec/request/military_information_request_spec.rb
> +        VCR.use_cassette('va_profile/post_read_service_history_403') do
You should also remove this. It doesn't cause an error because the call is never made so VCR never tries to load it.

2023-03-27 22:44 UTC, aherzberg approved these changes
LGTM. I always forget the policies will prevent the VCRs from running.

2023-03-27 22:44 UTC, merged