13968 zipcode validation endpoint
department-of-veterans-affairs/vets-api pull request #13074
Opened 2023-06-22 19:35 UTC by jtmst

## Summary

- Gives the income limits module a separate endpoint for validating zip codes
- takes in a zip param
- Returns a bool response
- Sample request url:  `http://localhost:3000/income_limits/v1/validateZipCode/15212/`
- Sample response: `{
    "zip_is_valid": true
}`

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13968

## Testing done

- Local testing and added rspec tests

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Income limits module

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-06-23 16:00 UTC, rmtolmach submitted a review, later dismissed
LGTM

2023-06-23 20:05 UTC, maxx1128 requested changes
This looks good and the tests pass, I just have two small refactors and then it should be 100% good to go.

2023-06-23 20:05 UTC, maxx1128 commented on modules/income_limits/app/controllers/income_limits/v1/income_limits_controller.rb
> +        response = true if zipcode_data&.county_number
**Suggestion:** the response assignment could be refactored to use a ternary operator.

```ruby
response = zipcode_data&.county_number ? true : false
```

2023-06-27 09:49 UTC, maxx1128 approved these changes

2023-06-27 15:48 UTC, merged