db migrate for refresh token path client config ticket.
department-of-veterans-affairs/vets-api pull request #13101
Opened 2023-06-27 15:23 UTC by tynyttie

## Summary

This PR introduces the schema change component of the additional fields being added to the Client Config object, which allow for a optional refresh_token_cookie_path to client config. This path will be added to the refresh_token cookie when cookies are generated. If no cookie config is present default to the sign in service refresh path.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55778

[ZinHub: ticket 55778](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55778)

## Testing done
      Migrated schema and rolled back to confirm 2-way migration works

## What areas of the site does it impact?
Sign-in Service

## Acceptance criteria

  bundle exec rails db:migrate
  bundle exec rails db:rollback 
  Confirm no errors and schema changes as expected

2023-06-27 17:55 UTC, rileyanderson requested changes
You need to include the `schema.rb` changes

2023-06-28 14:36 UTC, rileyanderson requested changes

2023-06-28 14:36 UTC, rileyanderson commented on db/schema.rb
This needs to include the version change. This file is automatically generated when you migrate your database. You should not be manually editing this file.

2023-06-28 18:51 UTC, rileyanderson approved these changes

2023-06-30 17:49 UTC, ryan-mcneil approved these changes
👌

2023-06-30 17:53 UTC, merged