5934 use new clinics and providers caches
department-of-veterans-affairs/vets-api pull request #13113
Opened 2023-06-28 00:53 UTC by cadibemma

## Summary

- The VAOS team recently added a caches for clinics and providers and methods for fetching through the cache called `get_clinic_with_cache` and `get_provider_with_cache`. We should change the proxy to use that method, since it should provide some performance benefits.

## Related issue(s)
- department-of-veterans-affairs/va-mobile-app#5934

## Testing done
- Specs

## What areas of the site does it impact?
- None

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2023-07-06 20:38 UTC, kpethtel requested changes
Aside from that `require`, I think this is ready to go. Thanks for cleaning up the specs while you were there. I still think the stubbing in those specs is somewhat problematic because it's caused them to be very difficult to work in (as we both experienced), so I appreciate you at least removing the mocks where possible.

2023-07-06 20:38 UTC, kpethtel commented on modules/mobile/app/services/mobile/v2/appointments/proxy.rb
> +require 'mobile/v0/vaos_appointments/appointments_helper'
This require should not be necessary because it's within the rails app directory.

2023-07-06 20:57 UTC, Tonksthebear submitted a review, later dismissed
LGTM with Kris's change

2023-07-06 22:59 UTC, Tonksthebear approved these changes
LGTM

2023-07-07 22:18 UTC, kpethtel approved these changes
Thanks for going the extra mile.

2023-07-07 22:30 UTC, merged