Support pagination for /v0/onsite_notifications
department-of-veterans-affairs/vets-api pull request #13298
Opened 2023-07-18 18:02 UTC by dellerbie

Adds pagination support to `GET v0/onsite_notifications`

## Summary

- Added pagination support to `v0/onsite_notifications` via the `page` and `per_page` query params
- Updated Swagger docs

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/60639

## Screenshot
Updated Swagger Doc

<img width="595" alt="Screenshot 2023-07-19 at 1 49 11 PM" src="https://github.com/department-of-veterans-affairs/vets-api/assets/534756/3a9fde60-f9a4-4a95-963c-b1626788035b">

## Testing done

- Prior to the change there was no way to page through the results
- Postman to `GET /v0/onsite_notifications?page=1&per_page=2`

## What areas of the site does it impact?
The pagination feature will be used in the new Notification Center components

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

2023-07-18 22:01 UTC, tpharrison approved these changes

2023-07-19 13:17 UTC, jeremy6d requested changes
There's a few things that would help me approve this and understand the platform impact:
- there are no acceptance criteria on the originating ticket or on this PR, so I don't really understand _in detail_ what it means that this works
- additionally there are no tests added, no screenshots, nothing that gives me an understanding that what the PR author _thinks_ they did lines up with what they _actually_ did
- no testing instructions

2023-07-20 17:01 UTC, tpharrison approved these changes

2023-07-24 16:24 UTC, ryan-mcneil commented
@dellerbie I'm curious - what happens if someone was to include, say, the `optional_page_number` but not the `optional_page_length`. You have some good specs for the "happy path", but what happens when a user does something that's not expected? Are there defaults and checks for all of that? To be fair, I'm not picking through every piece of code, just going off of changes made and specs written. If you believe all cases are handled, this is good by me!

2023-07-24 18:53 UTC, ryan-mcneil approved these changes
Looks good! Yeah, I completely agree that it's not necessary to test libraries that are already thoroughly tested, but sometimes it doesn't hurt to test around the integration of said library 👌

2023-07-24 21:20 UTC, merged