MHV-48126 Call PHR refresh asynchronously after MHV user login
department-of-veterans-affairs/vets-api pull request #13693
Opened 2023-08-30 18:27 UTC by mmoyer-va

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintainence of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *Describe the tests completed and the results*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-08-31 14:34 UTC, tynyttie approved these changes
I approve these changes.

2023-08-31 16:51 UTC, LindseySaari approved these changes

2023-08-31 16:58 UTC, bosawt requested changes
Mainly just making sure `mhv_correlation_id` is what you actually want

2023-08-31 16:58 UTC, bosawt commented on app/services/login/after_login_actions.rb
> +                                        current_user.mhv_correlation_id)
I don't think you need to gate this on `mhv_correlation_id` if you're also checking it during the job itself

2023-08-31 23:58 UTC, bosawt commented
Also, I tested this locally and on prod and it doesn't seem to work in either case? At least the refresh functionality itself:

<img width="1232" alt="image" src="https://github.com/department-of-veterans-affairs/vets-api/assets/42326799/45025bc2-3f72-4bf2-9237-0d11985512f3">

2023-08-31 23:59 UTC, bosawt commented
We need to be extremely careful about the functionality that's added to auth, I would make sure this refresh is actually working through standard flows before introducing it to the authentication flow

2023-09-01 13:43 UTC, mmoyer-va commented on app/workers/mhv/phr_update_job.rb
> +      mhv_correlation_id.present?
Sure -- I only want to run this refresh for users who have an MHV account. I figured that the correlation ID will be present for all such users but if there is a better way I can make the switch!

2023-09-01 13:53 UTC, mmoyer-va commented
@bosawt You're right -- we haven't added the `x_auth_key` in production yet. It does work locally, but that param must be added to the settings.local.yml file.

However I don't think we want to run this in production before we enter Phase 0. We should turn off that feature flag in prod until that point.

2023-09-01 17:16 UTC, bosawt commented
> @bosawt You're right -- we haven't added the `x_auth_key` in production yet. It does work locally, but that param must be added to the settings.local.yml file.
> 
> However I don't think we want to run this in production before we enter Phase 0. We should turn off that feature flag in prod until that point.

Ah, I see, thanks for that context. So feature flags should be used to perform rollouts of code that's expected to work, not to hide code that doesn't currently work, especially in flows that are currently live (and heavily trafficked like this). I think we should revisit the concept of adding it here once this refresh is working and you are at a phase where you'd like it to be added.

2023-10-05 16:11 UTC, mmoyer-va commented
@bosawt I'd like to revisit this PR. The `x_auth_key` has been added to the parameter store for production, and the SideKiq job has been tested in staging (currently being run when a user accesses the MR page). Let me know what other concerns you have so we can discuss, as there is a strong desire to move this action left as far as possible. Otherwise users may see an empty list when in fact they have records.

2023-11-14 20:11 UTC, ericboehs commented
Moving to draft to remove from review queue.

2024-01-11 20:32 UTC, closed without merging