Feature route single new
department-of-veterans-affairs/vets-api pull request #13938
Opened 2023-09-26 11:08 UTC by lukey-luke

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- The purpose of this PR is to allow single-issue NEW 526-ez claims to be routed to Contention Classification service in VRO
- removed old feature flag (for routing claims for increase)
- add new feature flag for NEW claims
- update guards for [Form526ClaimFastTrackingConcern.update_classification](https://github.com/department-of-veterans-affairs/vets-api/blob/feature-route-single-new/app/models/concerns/form526_claim_fast_tracking_concern.rb#L115) accordingly
- flipper is used for the new feature flag, will submit a follow up PR after NEW traffic is routed to VRO

## Related issue(s)
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/260
- after this PR is merged, follow-up: https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/242

## Testing done

- Previously, 526Submission sidekiq job would check for 1. old feature flag and 2. that the claims was a single-issue claim for increase
- Now sidekiq job checks that claim is 1. single issue and 2. NEW or increase. 3. If it's a NEW claim, it checks that the new feature flag is toggled on
- testing done via rspec, see `bundle exec rspec spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb`

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [X]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
  - I believe this is n/a?
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
 - PII is sent to VRO, but not logged, specifically [contention_text](https://github.com/department-of-veterans-affairs/vets-api/blob/feature-route-single-new/app/models/concerns/form526_claim_fast_tracking_concern.rb#L128) for new claims
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
  - n/a
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
  - n/a
- [ ]  I added a screenshot of the developed feature
  - n/a

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-09-26 15:39 UTC, lukey-luke commented
🤯

```
Your branch is up to date with 'origin/feature-route-single-new'.
verdanceluke@Verdances-MacBook-Pro vets-api % bundle exec rspec spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 60337
...........

Finished in 9.44 seconds (files took 6.71 seconds to load)
11 examples, 0 failures

Randomized with seed 60337

Coverage report generated for RSpec to /Users/verdanceluke/code/vets-api/coverage. 8896 / 107864 LOC (8.25%) covered.
```

2023-09-26 16:05 UTC, lukey-luke commented
> 🤯
> 
> ```
> Your branch is up to date with 'origin/feature-route-single-new'.
> verdanceluke@Verdances-MacBook-Pro vets-api % bundle exec rspec spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
> Run options: include {:focus=>true}
> 
> All examples were filtered out; ignoring {:focus=>true}
> 
> Randomized with seed 60337
> ...........
> 
> Finished in 9.44 seconds (files took 6.71 seconds to load)
> 11 examples, 0 failures
> 
> Randomized with seed 60337
> 
> Coverage report generated for RSpec to /Users/verdanceluke/code/vets-api/coverage. 8896 / 107864 LOC (8.25%) covered.
> ```

fix'd, just had to update with base branch

2023-09-26 16:44 UTC, tyler-spangler6 approved these changes
Looks good and changes make sense with the caveat that I am new to Ruby so could have missed something during my review.

2023-09-27 15:29 UTC, sethdarragile6 approved these changes

2023-09-27 17:11 UTC, lukey-luke commented on spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
> +    # rails.error statements will cause expect_retryable_error to fail in these tests
should read
"    # this is a workaround to ensure Contention Classification API in VRO does not get called, because"

2023-09-28 19:08 UTC, GcioNapoleon approved these changes

2023-09-28 19:33 UTC, rmtolmach requested changes
Please fix merge conflict. The number of files changed isn't right, either 😕

2023-09-29 16:26 UTC, lukey-luke commented
closed in favor of https://github.com/department-of-veterans-affairs/vets-api/pull/13971

2023-09-29 16:26 UTC, closed without merging