[DBX-66487] fix 526 backup retry validation failure bug
department-of-veterans-affairs/vets-api pull request #14007
Opened 2023-10-02 21:07 UTC by SamStuckey

## Summary

-  Replace `create!` (creation) of Form526JobStatus instance with an "upsert" style creation which will respect an existing records uniqueness rights relative to it's calling sidekiq job id (aka `jid`).  This logic mirrors what we are doing in other places with this model, i.e. inside our `with_tracking` helper. 

## Related issue(s)
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/66487)

## Testing done

- Manually run worker locally
- Manually run code samples

## What areas of the site does it impact?
526 backup submission

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2023-10-03 17:17 UTC, NB28VT requested changes
This looks good and the logic for this style of creation makes sense. 

Should probably have some tests though for the existing/not existing status situations for extra safety. That's getting a little into just testing Rails works lol but would catch issues in the future like uniqueness constraints we put on certain attributes for example or other validations.

Another improvement could be extracting the hardcoded job_class arg 'BackupSubmission' to a constant for better visibility.

2023-10-03 17:49 UTC, SamStuckey commented
@NB28VT THis functionality is already extensivly tested in this file:
`spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb`
The only thing we are changing is the implementation, which is not a change that has a visible effect.  The thing we could test is where we try to recreate this bug, however it would be relatively contrived.  I think given the time sensitive nature of this work as well as the massive potential improvement we should push this through.

2023-10-03 18:03 UTC, NB28VT approved these changes
Thanks for following up on the tests, sounds good

2023-10-03 19:00 UTC, aurora-a-k-a-lightning approved these changes

2023-10-05 17:02 UTC, rmtolmach approved these changes

2023-10-06 14:30 UTC, merged