Adds /v0/profile/contacts, mocked VA Profile Health Benefit service
department-of-veterans-affairs/vets-api pull request #14024
Opened 2023-10-03 21:42 UTC by radavis

## Summary

- Adds `GET /v0/profile/contacts`, returning Next-of-kin and Emergency Contact records for a Veteran
- Feature controlled with feature toggle: `profile_contacts`
- Adds `VAProfile::HealthBenefit::Service` and supporting code for a planned future integration. Responds with mock data

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#66602

## Testing done

- *Describe what the old behavior was prior to the change*
  - Prior behavior: `GET /v0/profile/contacts` returns 4xx.
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
  - To verify: Sign in and visit `/v0/profile/contacts`. Two mocked records will be returned.
- *Describe the tests completed and the results*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
- `/v0/profile` namespace

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-10-09 14:11 UTC, rmtolmach commented
👋 I merged some rspec changes on Friday. I wanted to be sure your branch was up-to-date so it would catch any errors pre-merge, so that's why I merged master into your branch.

2023-10-12 17:11 UTC, RachalCassity submitted a review, later dismissed

2023-10-12 17:47 UTC, tpharrison reviewed
Just two things we chatted about:
- Keep `vfs-authenticated-experience-backend` as codeowners, but also add your team
- Change `ContactInformationController` to `AssociatedPersonsController`.  This is just a suggestion based on what we may build going forward.

2023-10-13 14:18 UTC, radavis commented
>     * Change `ContactInformationController` to `AssociatedPersonsController`.  This is just a suggestion based on what we may build going forward.

Hey @tpharrison, I have a `ContactsController` and an API path named `/v0/profile/contacts`. Does that pose any conflicts with what you anticipate adding to `/v0/profile`?

2023-10-13 15:24 UTC, tpharrison commented
> > ```
> > * Change `ContactInformationController` to `AssociatedPersonsController`.  This is just a suggestion based on what we may build going forward.
> > ```
> 
> Hey @tpharrison, I have a `ContactsController` and an API path named `/v0/profile/contacts`. Does that pose any conflicts with what you anticipate adding to `/v0/profile`?

That works 👍

2023-10-19 20:15 UTC, radavis commented
> 1 Error
> 🚫 	New entry on line 9 of CODEOWNERS does not include @department-of-veterans-affairs/backend-review-group.
> Please add @department-of-veterans-affairs/backend-review-group to the entry
> Offending line: `app/controllers/v0/profile/contacts_controller.rb @department-of-veterans-affairs/vfs-authenticated-experience-backend @department-of-veterans-affairs/vfs-health-modernization-initiative`
> 	1 Warning
> ⚠️ 	This PR changes `399` LoC (not counting whitespace/newlines).
> 
> Generated by 🚫 [Danger](https://danger.systems/)

I can change this, but _should_ **I** be changing this?

2023-10-20 17:02 UTC, tpharrison requested changes

2023-10-20 17:02 UTC, tpharrison commented on run
Should platform review this?

2023-10-23 12:41 UTC, radavis commented on run
Removed this file.

2023-10-23 14:39 UTC, tpharrison approved these changes

2023-10-23 15:11 UTC, RachalCassity commented on .github/CODEOWNERS
Thank you for updating this file. :)

2023-10-23 18:15 UTC, beaugrantham-va approved these changes
Lighthouse is unaffected by this PR.

2023-10-23 19:38 UTC, radavis commented
lighthouse-banana-peels team is being asked to review because of this line in `.github/CODEOWNERS`

```
# line: 37
app/controllers/v0/apidocs_controller.rb @department-of-veterans-affairs/lighthouse-banana-peels
```

Disability-Experience team is being asked to review because of this line in `.github/CODEOWNERS`

```
# line: 927
lib/va_profile @department-of-veterans-affairs/Disability-Experience @department-of-veterans-affairs/vfs-authenticated-experience-backend @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
```

2023-10-24 13:43 UTC, RachalCassity approved these changes

2023-10-24 14:01 UTC, merged

2023-10-24 14:03 UTC, tommasina-va commented on config/routes.rb
> +  # end /v0
I think we can probably remove this?