Add Logs to ch36 Workflow
department-of-veterans-affairs/vets-api pull request #14392
Opened 2023-11-02 23:42 UTC by DLarson-Oddball

## Summary

Adds logs to ch36 workflow creating team visibility into submission failure and success rates.
Adds log to ch31 case where participant_id is blank.

## Related issue(s)
- [ department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67879)

## Testing done

- Tested flow using debugger to ensure code runs correctly.

## What areas of the site does it impact?
Ch36 submission background job

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2023-11-02 23:48 UTC, micahaspyr requested changes
Only suggestion is to change :warn to :error

2023-11-02 23:48 UTC, micahaspyr commented on app/sidekiq/central_mail/submit_career_counseling_job.rb
> +        log_message_to_sentry('Error submitting form 25-8832', :warn, { uuid: user_uuid })
Change :warn to :error

2023-11-02 23:57 UTC, micahaspyr approved these changes
LGTM

2023-11-03 13:52 UTC, tblackwe approved these changes

2023-11-03 16:35 UTC, ryan-mcneil approved these changes
👍

2023-11-03 16:35 UTC, merged