APIv000 veteran verification removal
department-of-veterans-affairs/vets-api pull request #14610
Opened 2023-11-21 18:39 UTC by dmekala-va

## Summary

- This PR is to remove veteran verification files and rspecs in preparation for deleting the openId_application controller. These files use the openid_application controller therefore the goal is to remove all files that include reference to it and ultimately remove the file. 
- Lighthouse Team Pivot!

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#[API-20648]
- https://jira.devops.va.gov/browse/API-20648
- This relates to the above links and in preparation for the story

## Testing done

- Deleting rspecs and relevant vcr cassettes not used anymore

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-11-21 18:57 UTC, jperk51 requested changes
I'm not really sure I understand what's going on here, but deleting stuff from the mobile module seems dangerous without adding and rerouting to the replacement logic. Have we confirmed that none of the veterans_verification logic is currently being used in prod?

2023-11-21 20:27 UTC, kpethtel reviewed
To @jperk51 's point, can you tell us which part of our user request spec is problematic? Perhaps we can just remove that and not the entire file.

2023-11-21 20:40 UTC, dmekala-va commented
> To @jperk51 's point, can you tell us which part of our user request spec is problematic? Perhaps we can just remove that and not the entire file.



> To @jperk51 's point, can you tell us which part of our user request spec is problematic? Perhaps we can just remove that and not the entire file.

Yes np. Will add that file back in and modify to fit the veteran verification file removals

2023-11-27 14:19 UTC, dbrown-va commented
The `modules/mobile/spec/request/user_request_spec.rb` modification was reverted.  

This change is isolated to the Veteran Verification V0 module removal which has been completed removed from Lighthouse routing and all traffic confirmed to the DVP deployed microservice.

2023-11-27 14:46 UTC, crolarlibertyva submitted a review, later dismissed

2023-11-27 14:51 UTC, crolarlibertyva approved these changes

2023-11-27 16:58 UTC, jerekshoe requested changes

2023-11-27 16:58 UTC, jerekshoe commented on app/controllers/v0/rated_disabilities_controller.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on app/controllers/v0/rated_disabilities_discrepancies_controller.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on lib/disability_compensation/factories/api_provider_factory.rb
> -require 'disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider'
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on lib/disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on lib/lighthouse/veteran_verification/configuration.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/controllers/v0/disability_compensation_forms_controller_spec.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/lib/lighthouse/veteran_verification/service_spec.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/models/form526_submission_spec.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/requests/v0/disability_compensation_in_progress_forms_controller_request_spec.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/requests/disability_compensation_form_request_spec.rb
> -# frozen_string_literal: true
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_Not_Connected_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/400_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/401_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/403_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/404_ICN_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/404_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/405_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/413_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/429_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/500_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/502_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/503_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/504_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 16:58 UTC, jerekshoe commented on spec/support/vcr_cassettes/lighthouse/veteran_verification/show/200_response.yml
> ----
This file is not related to the lighthouse module and should not be removed

2023-11-27 17:28 UTC, dmekala-va commented
Added back all files not related to VV module removal

2023-11-27 19:07 UTC, crolarlibertyva approved these changes

2023-11-27 21:00 UTC, dmekala-va commented
Would I be able to get another review please? @jerekshoe and @jperk51

2023-11-28 14:37 UTC, rjohnson2011 approved these changes

2023-11-28 14:58 UTC, crolarlibertyva approved these changes

2023-11-28 16:15 UTC, jperk51 approved these changes

2023-11-28 17:22 UTC, kpethtel approved these changes

2023-11-28 17:49 UTC, jerekshoe submitted a review, later dismissed

2023-11-30 18:26 UTC, closed without merging