[70539] Validate access_token_attributes for ServiceAccountConfig model
department-of-veterans-affairs/vets-api pull request #14639
Opened 2023-11-24 18:28 UTC by dickdavis

## Summary

This PR validates the contents of the `access_token_attributes` field against a JSON schema which defines allowed values.

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#70539

## Testing done

- Use the Rails console to load a service account config.
```ruby
config = SignIn::ServiceAccountConfig.last
```
- Attempt to store an invalid value (`{ foo: bar }`)
```ruby
config.access_token_attributes = { foo: 'bar' }
```
- Verify the validation fails.
- Attempt to store a valid value (`{ user_attributes: { icn: '123' } }`)
```ruby
config.access_token_attributes = { user_attributes: { icn: '123' } }
```
- Verify the validation succeeds.

## Screenshots
Not relevant.

## What areas of the site does it impact?
This PR impacts service account authentication.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-11-27 16:36 UTC, bramleyjl approved these changes

2023-12-01 16:41 UTC, bosawt commented on spec/factories/sign_in/service_account_configs.rb
>      access_token_duration { SignIn::Constants::AccessToken::VALIDITY_LENGTH_SHORT_MINUTES }
We should use your new constant for this field

2023-12-01 16:48 UTC, bosawt commented on app/services/sign_in/constants/service_account_access_token.rb
> +    module ServiceAccountAccessToken
We might as well go ahead and copy the rest of the access token constants into this and refer to this set of constants wherever we use the service account functionality

If you do a global search for `Constants::AccessToken` you should be able to see everywhere that needs to be changed to the service account access token without too much difficulty (I only see ~50 usages so not too huge)

2023-12-01 16:48 UTC, bosawt requested changes
Mostly looks good, just some simple changes around using the constants more consistently.

2023-12-04 16:48 UTC, kpethtel approved these changes
Good AFAICT

2023-12-04 18:22 UTC, bramleyjl submitted a review, later dismissed
Thanks for updating the service account constants!

2023-12-04 19:43 UTC, bosawt approved these changes
looks gud. Tested by attempting to create a ServiceAccount Config with user attributes that aren't `ICN` (which properly failed), and attempting to create a ServiceAccountConfig with `ICN` user attribute (which worked)

2023-12-04 20:35 UTC, rjohnson2011 approved these changes

2023-12-04 21:04 UTC, merged