Api 32376 null value handling pdf generator
department-of-veterans-affairs/vets-api pull request #15005
Opened 2024-01-02 15:27 UTC by mchristiansonVA

## Summary

- Adds null handling to pdf mapper logic so that null value errors are not thrown by the PDF Generator when submitting a 526 request with [Optional Null Attributes](https://confluence.devops.va.gov/display/VAExternal/526+v2+Testing#id-526v2Testing-OptionalNullAttributes).
- Fixes handling for nil treatment center name.
- Fixes handling for nil values for multiple exposures section of toxic exposure.

## Related issue(s)
[API-32376](https://jira.devops.va.gov/browse/API-32376)

## Testing done

- Testing in Postman using the [Optional Null Attributes](https://confluence.devops.va.gov/display/VAExternal/526+v2+Testing#id-526v2Testing-OptionalNullAttributes) submission
- Rspec tests added for mapping elements with null values for treatments, multiple exposures.

## What areas of the site does it impact?
modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2024-01-02 18:05 UTC, stiehlrod approved these changes

2024-01-08 15:56 UTC, rockwellwindsor-va reviewed
Getting an error `undefined method `length' for nil:NilClass` , pdf mapper line 223, when using null values for`herbicideHazardService`. 

```
        "herbicideHazardService": {
          "servedInHerbicideHazardLocations": null,
          "otherLocationsServed": null,
          "serviceDates": {
            "beginDate": null,
            "endDate": null
          }
        },
```

2024-01-08 21:47 UTC, stiehlrod requested changes
![Screenshot 2024-01-08 at 2 46 51 PM](https://github.com/department-of-veterans-affairs/vets-api/assets/25069483/e10b9083-8368-4d26-a30a-bd00ae9aed53)

2024-01-09 17:31 UTC, stiehlrod approved these changes

2024-01-09 18:22 UTC, merged