Add pension specific sentry tag
department-of-veterans-affairs/vets-api pull request #16040
Opened 2024-03-21 18:51 UTC by scottsdevelopment

## Summary

- Add a pension specific sentry tag

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#77413

2024-03-21 20:07 UTC, wayne-weibel requested changes
Please, also add the Sentry tag to `app/sidekiq/lighthouse/pension_benefit_intake_job.rb` at the start of the `perform` function

2024-03-21 20:07 UTC, wayne-weibel commented on app/controllers/v0/pension_claims_controller.rb
> +require 'pension_21p527ez/tag_sentry'
this should not be necessary.  i think there is some 'magic' naming convention setup to automatically load modules in ruby (would need to investigate that)

2024-03-25 15:56 UTC, wayne-weibel approved these changes

2024-03-25 17:12 UTC, LindseySaari approved these changes

2024-03-26 16:33 UTC, merged