new pdf version adding text field for place and location of death. ha…
department-of-veterans-affairs/vets-api pull request #16093
Opened 2024-03-26 19:07 UTC by evansmith

…ndle pdf filler. spec tests

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *This work is behind a feature toggle (flipper): YES*
-Update to the 21P-530V2, an additional field needed to be added to the pdf and then populated through pdf filler. There are multiple special cases for question 20B: location of death where a facility name and location need to be added. This is an addition to the work handled in: https://github.com/department-of-veterans-affairs/vets-api/pull/15838
- *(If bug, how to reproduce)*
- If certain options are chosen, we write to the pdf key where a facility name and location can be entered. Special case handing for selecting atHome. 
- VA Benefits and Claims
- Completion of Staging Review

## Related issue(s)

[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71046)
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [x] *New code is covered by unit tests*
- Fill out a 21P-530V2 and check off nursingHomeUnpaid. This will prompt a location and facility field to appear. Populate those and when examining the pdf all value should be entered.
- *If this work is behind a flipper:*
  - This form is only applicable when the va_burial_v2 flipper is on, flipper is not added in spec.

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
Burials V2

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-27 20:55 UTC, stevenjcumming requested changes

2024-03-27 20:55 UTC, stevenjcumming commented on lib/pdf_fill/forms/va21p530v2.rb
> +          location_of_death['placeAndLocation'] = "#{location_of_death[location_of_death['location']]['facilityName']} - #{location_of_death[location_of_death['location']]['facilityLocation']}"
`rubocop:disable Layout/LineLength` is not appropriate in this situation. Please break up line 581 into multiple lines

2024-03-27 21:49 UTC, tblackwe approved these changes

2024-03-28 18:21 UTC, stevenjcumming approved these changes

2024-03-28 18:44 UTC, merged