[DR-65545] Log KPIs for Supplemental Claims (contestable issues)
department-of-veterans-affairs/vets-api pull request #16179
Opened 2024-04-02 19:57 UTC by anniebtran

## Summary

Follow-up to #16176 to make things a little easier to review. This covers adding logging to SC contestable issues

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/65545

## Testing done

- [x] *New code is covered by unit tests*
- [x] Tested that API call works locally.
- Will do a test on staging to check that uploads/form submission both work and logs are showing up in DataDog as expected

## What areas of the site does it impact?
The Supplemental Claims form 

## Acceptance criteria
 - [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
 - [x] No error nor warning in the console.
 - [x] Events are being sent to the appropriate logging solution
 - [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
 - [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

2024-04-03 14:29 UTC, Mottie submitted a review, later dismissed

2024-04-03 16:06 UTC, dfong-adh approved these changes

2024-04-03 16:53 UTC, stevenjcumming requested changes

2024-04-03 16:53 UTC, stevenjcumming commented on spec/requests/v1/supplemental_claims/contestable_issues_controller_request_spec.rb
> +                                                    })
Please move the hashes to a variable or method

2024-04-04 18:25 UTC, dfong-adh approved these changes

2024-04-04 18:27 UTC, stevenjcumming approved these changes
👍

2024-04-04 19:22 UTC, merged