[DR-65545] Log KPIs for Supplemental Claims (create + upload evidence)
department-of-veterans-affairs/vets-api pull request #16176
Opened 2024-04-02 15:50 UTC by anniebtran

## Summary
In #13973, Eugene added more comprehensive logging for our NOD form — this adds similar logging for Supplemental Claims. I'm opening a follow-up PR to add logging to contestable issues

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/65545

## Testing done

- [x] *New code is covered by unit tests*
- [x] Tested that evidence uploads and form submission works locally. 
- Will do a test on staging to check that uploads/form submission both work and logs are showing up in DataDog as expected

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*
The Supplemental Claims form and some code shared between SC and NOD

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)

2024-04-02 15:51 UTC, anniebtran commented on spec/sidekiq/decision_review/submit_upload_spec.rb
> +                                                              body: anything # why isn't this working?
for some reason this `anything` matcher isn't working even though it's pretty much the same test as the one above for NOD — anyone have ideas for what might be happening here?

2024-04-02 15:53 UTC, anniebtran commented on spec/support/vcr_cassettes/decision_review/SC-PUT-UPLOAD-503_V1.yml
> +---
pretty much the same as `NOD-PUT-UPLOAD-503.yml`

2024-04-02 17:15 UTC, anniebtran commented on spec/sidekiq/decision_review/submit_upload_spec.rb
> +                                                              body: anything # why isn't this working?
nvm i figured out what was actually not matching up!

2024-04-02 18:46 UTC, anniebtran commented on spec/sidekiq/decision_review/submit_upload_spec.rb
> +    context 'Supplemental Claims - when file_data exists' do
These are largely the same tests as above, just with the Supplemental Claims form id instead of NOD's

2024-04-03 13:07 UTC, stevenjcumming commented
@anniebtran Please ask a teammate for a review, then I can review this.

2024-04-03 16:21 UTC, dfong-adh submitted a review, later dismissed

2024-04-03 16:51 UTC, stevenjcumming requested changes

2024-04-04 18:24 UTC, dfong-adh approved these changes

2024-04-04 18:26 UTC, stevenjcumming approved these changes

2024-04-04 19:04 UTC, merged