[78699] adds csps and acrs attributes to ClientConfig
department-of-veterans-affairs/vets-api pull request #16238
Opened 2024-04-08 15:29 UTC by bramleyjl

## Summary

- Adds `csps` and `acrs` attributes to SignIn::ClientConfig. These attributes will be validated against requested CSP and ACR during `/authorize` to allow SiS clients to prevent certain CSPs or ACRs from use.
- `csps` default values: [ 'logingov', 'idme', 'dslogon', 'mhv']
- `acrs` default values: [ 'ial1', 'ial2', 'loa1', 'loa3', 'min']

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78699

## Testing done

- Confirmed new attributes were present with default on existing & newly created ClientConfigs.

2024-04-08 20:26 UTC, bosawt requested changes
Just small naming preference changes

2024-04-08 20:26 UTC, bosawt commented on db/migrate/20240408152120_add_csps_acrs_to_client_configs.rb
> +    add_column :client_configs, :acrs, :string, array: true, default: %w[ial1 ial2 loa1 loa3 min]
can we call this column `service_levels`

2024-04-08 20:26 UTC, bosawt commented on db/migrate/20240408152120_add_csps_acrs_to_client_configs.rb
> +    add_column :client_configs, :csps, :string, array: true, default: %w[logingov idme dslogon mhv]
can we call this column `credential_service_providers`

2024-04-09 19:08 UTC, ericboehs approved these changes

2024-04-09 19:14 UTC, merged