Vfep 903 - add guardian certification/signature to 1995 spool file
department-of-veterans-affairs/vets-api pull request #16265
Opened 2024-04-09 20:12 UTC by GcioGregg

Vfep 903 - add guardian certification/signature to 1995 spool file

## Summary

- *This work is behind a feature toggle (flipper): YES*
- added conditional statement by signature if Guardian is present
- VFEP
- feature flag will be removed upon user acceptance

## Related issue(s)

- [vfep-903](https://jira.devops.va.gov/browse/VFEP-903)
- [github 16264](https://github.com/department-of-veterans-affairs/vets-api/issues/16264)

## Testing done

- [x] *New code is covered by unit tests*
- 1995 spool file did not contain new statement when guardian present
- generate 1995 spool file and confirm new statement is there when guardian is present
- user testing of all recent 1995 spool changes on staging, once approved feature flag will be removed

## What areas of the site does it impact?
impacts 1995 spool file

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2024-04-09 21:10 UTC, nfstern02 approved these changes

2024-04-09 21:44 UTC, ericboehs commented on Gemfile.lock
> +
Can we remove this extra new line?

2024-04-09 21:48 UTC, ericboehs commented on app/sidekiq/education_form/templates/1995.erb
> +<%= parse_with_template_path('footer') %>
This file is missing a final new line. If you're using VS Code: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

2024-04-09 21:48 UTC, ericboehs requested changes
newline stuff

2024-04-10 20:02 UTC, ryan-mcneil approved these changes
👍

2024-04-10 20:04 UTC, nfstern02 submitted a review, later dismissed

2024-04-10 20:21 UTC, bradbergeron-us approved these changes

2024-04-10 21:03 UTC, ryan-mcneil approved these changes
LGTM

2024-04-10 21:03 UTC, merged