80453 create a method to upsert IPFs based on 5655 metadata
department-of-veterans-affairs/vets-api pull request #16386
Opened 2024-04-17 19:06 UTC by kjsuarez

## Summary
Add logic to upsert an InProgressForm based on a previous 5655 submission.

## Related issue(s)
[80453](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/80453)

## Testing done
Specs added

## What areas of the site does it impact?
These endpoints aren't currently in use but they will eventually be used by the debt portal and FSR submission workflow.

## Acceptance criteria
- [ ] Provide a means to reset a given user's 5655 InProgressForm data based on the data used to submit a previous FSR.

2024-04-17 19:15 UTC, OptionSelect submitted a review, later dismissed
LGTM! 🚀

2024-04-17 21:08 UTC, rileyanderson requested changes

2024-04-17 21:08 UTC, rileyanderson commented on modules/debts_api/app/models/debts_api/v0/form5655_submission.rb
> +                                    )
You can accomplish the same thing with:
```ruby
InProgressForm.find_or_initialize_by(form_id: '5655', user_uuid:)
```

2024-04-18 15:11 UTC, rileyanderson approved these changes

2024-04-18 17:43 UTC, rmtolmach approved these changes

2024-04-23 13:55 UTC, merged