manila timezone info logging
department-of-veterans-affairs/vets-api pull request #16468
Opened 2024-04-23 19:07 UTC by cferris32

## Summary

- This work is to implement investigative logging into the timezone info returned for the Manila, Philippines facility location

## Testing Done
- New test to verify logging functionality, ran regression tests on preexisting functionality

2024-04-23 19:38 UTC, jperk51 requested changes
I would also be interested in logging the outcome of `convert_utc_to_local_time(appt[:start], facility_timezone)`

2024-04-23 21:53 UTC, cferris32 commented
> I would also be interested in logging the outcome of `convert_utc_to_local_time(appt[:start], facility_timezone)`

This should be addressed now

2024-04-24 02:09 UTC, jperk51 approved these changes

2024-04-24 12:53 UTC, rmtolmach reviewed
This LGTM but you probably want someone from @department-of-veterans-affairs/vfs-vaos to review since they're the primary codeowners of both files in this PR.

2024-04-24 15:00 UTC, simiadebowale approved these changes

2024-04-24 15:05 UTC, merged