Add boilerplate for income and assets pdf mapping and tests.
department-of-veterans-affairs/vets-api pull request #17072
Opened 2024-06-10 18:17 UTC by scottsdevelopment

## Summary

- Add boilerplate code for income and assets PDF mapping.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#82562

## Testing done

- Created new unit tests and fixtures

2024-06-11 16:03 UTC, TaiWilkin commented on Gemfile.lock
> -  sidekiq-ent!
Make sure you don't merge any changes to Sidekiq enterprise/pro (see [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/base-setup-vets-api),  step 3).

2024-06-11 16:27 UTC, TaiWilkin requested changes
The code is working well - just need to clean up your Gemfile.lock file. 
Since this hasn't been hooked up yet (I presume because it will be called in the new intake job, which doesn't exist yet), I added a comment on the issue for the intake job linking to this PR for future reference.

2024-06-12 17:17 UTC, wayne-weibel requested changes
I fixed the Gemfile.lock, but now see some failing tests.  Once those are fixed this should be ready

2024-06-13 18:18 UTC, TaiWilkin approved these changes
Tests are passing, and the Gemfile.lock issue is corrected.

2024-06-14 16:11 UTC, wayne-weibel approved these changes

2024-06-14 19:36 UTC, ryan-mcneil approved these changes
👍

2024-06-14 19:48 UTC, merged