80989: Add logic for multiple PDFs
department-of-veterans-affairs/vets-api pull request #17076
Opened 2024-06-10 23:00 UTC by balexandr

Some forms have multiple applicants and we want to save the Veteran from going through the same form X times so this should make it easier and generates additional PDFs with common and new data

## Summary

- Add flexible functionality to allow multiple pdfs to be generated

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80989

## Testing done

- Rspec
- Browser 

## Screenshots
This is the first form with 3 applicants
![Screenshot 2024-06-10 at 6 58 19 PM](https://github.com/department-of-veterans-affairs/vets-api/assets/1422922/30c233c4-8703-4c0e-9346-02e3fa95a420)

This is the same form with 3 other applicants
![Screenshot 2024-06-10 at 6 58 46 PM](https://github.com/department-of-veterans-affairs/vets-api/assets/1422922/dbc645e4-667a-4d60-b4b8-b28a2f8f7ef9)

## What areas of the site does it impact?
Just IVC Forms

2024-06-10 23:01 UTC, balexandr commented on modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
> +
These constants exist so that the functionality can differ between forms. For 10-7959A this might change to '1' and 'claimant'

2024-06-10 23:35 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/attachments.rb
In the get_attachments method, you're using defined? to check if certain constants are defined. However, it's generally better to use const_defined? instead, as it specifically checks for the existence of a constant.

2024-06-11 01:00 UTC, balexandr commented on modules/ivc_champva/app/services/ivc_champva/attachments.rb
It doesn't really matter in this case because I'm explicit in the checking and there aren't any speed differences.

2024-06-11 11:05 UTC, cloudmagic80 commented
In the E2E test, I can't enter more that 3 applicants. Please work with front end to adjust the maximum number of applicants.
<img width="671" alt="Screenshot 2024-06-11 at 6 00 16 AM" src="https://github.com/department-of-veterans-affairs/vets-api/assets/99479640/12fdacad-eebc-4d96-93ed-3588b74f00fd">

2024-06-11 11:06 UTC, cloudmagic80 requested changes
Is there a corresponding branch in the front end? In the utilities file, we need to change  `export const MAX_APPLICANTS = 6;`

2024-06-11 11:55 UTC, cloudmagic80 commented
In the metadata portion, the attachment_id need to be adjusted to count in the additional pdf page.

2024-06-11 11:56 UTC, cloudmagic80 requested changes
Need to make adjustments to the metadata's attachment_id to include the additional page

2024-06-11 14:28 UTC, balexandr commented
> In the E2E test, I can't enter more that 3 applicants. Please work with front end to adjust the maximum number of applicants. <img alt="Screenshot 2024-06-11 at 6 00 16 AM" width="671" src="https://private-user-images.githubusercontent.com/99479640/338556403-12fdacad-eebc-4d96-93ed-3588b74f00fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTYzNDEsIm5iZiI6MTcxODExNjA0MSwicGF0aCI6Ii85OTQ3OTY0MC8zMzg1NTY0MDMtMTJmZGFjYWQtZWViYy00ZDk2LTkzZWQtMzU4OGI3NGYwMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZGJjN2EwOWY4MDBjMDJkMDFiMWVkMjcwNjE4YTkxOWFkNmFmMzRmNDYwNWQ2Y2JjYmE0MGJkMmIzZjhiMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92pemK7h8jOrNKELbsrGQGI3_wifFSsMBRFD0LLWKmc">

This is just the BE piece and will still function normally without the FE piece in place but yeah we need a FE ticket

2024-06-11 14:44 UTC, balexandr commented
> Is there a corresponding branch in the front end? In the utilities file, we need to change `export const MAX_APPLICANTS = 6;`

Yeah need FE to work on that still

2024-06-11 14:56 UTC, balexandr commented
> Need to make adjustments to the metadata's attachment_id to include the additional page

You have the most intimate knowledge of that piece. Know what has to be added/removed to make it count or skipped?

2024-06-15 02:24 UTC, cloudmagic80 submitted a review, later dismissed

2024-06-25 13:31 UTC, rmtolmach commented
@balexandr this PR is showing zero files changed. Please close if it's no longer needed.

2024-08-03 20:32 UTC, closed without merging