87181: Port over SimpleForm PDF stamp/filler changes with tests
department-of-veterans-affairs/vets-api pull request #17317
Opened 2024-06-28 14:49 UTC by balexandr

Bug description:
The signature field on the PDF for 10-10d is technically @type="Signature, rather than @type=Text. This causes our PDF filler functionality to skip over it.

## Summary

- Port over updates from SimpleForms for PDF Filler
- Port over updates from SimpleForms for PDF Stamper
- Updated tests
- Update models to use new format

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87181

## Testing done

- [x] *New code is covered by unit tests*

## Screenshots
<img width="830" alt="Screenshot 2024-06-28 at 10 49 01 AM" src="https://github.com/department-of-veterans-affairs/vets-api/assets/1422922/01298f89-ce8a-46eb-8970-78bf2b701486">

2024-06-28 14:50 UTC, balexandr commented on modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
> -          render json: { error_message: 'An unknown error occurred while uploading document(s).' },
Might help if we have a real error message to reference

2024-06-28 14:51 UTC, balexandr commented on modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb
> -    def submission_date_config
Removed all old logic that doesn't do anything. Stamp was set up false anyways.

2024-06-28 14:52 UTC, balexandr commented on modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
> -    def submission_date_config
Same

2024-06-28 15:07 UTC, michaelclement approved these changes

2024-06-28 16:18 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb
Why didn't you include 7959c, 7959a, and 7959f2?

2024-06-28 16:26 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
For the file deletion, your approach is safer because it is checking file existence before operations. One bad side is that your approach isn't generally more robust, the previous approach using ensure can cleanup even in error cases.

2024-06-28 16:28 UTC, balexandr commented on modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb
We only need to stamp ones that don't work normally.

2024-06-28 16:29 UTC, balexandr commented on modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
This was ported over from SimpleForms which has already been tested since they are in a live env. Seemed safer to keep their changes

2024-06-28 16:33 UTC, cloudmagic80 requested changes

2024-06-28 16:33 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
You deleted `ensure` and made changes to pdfiller. Why can't we leave it as is?

2024-06-28 17:46 UTC, cloudmagic80 requested changes

2024-06-28 17:46 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
I would put ```   if File.exist? stamped_template_path
    begin
      PdfStamper.stamp_pdf(stamped_template_path, form, current_loa)
      pdftk = PdfForms.new(Settings.binaries.pdftk)
      pdftk.fill_form(stamped_template_path, generated_form_path, mapped_data, flatten: true)
      generated_form_path
    ensure
      Common::FileHelpers.delete_file_if_exists(stamped_template_path)
    end
  else ```

2024-06-28 17:46 UTC, cloudmagic80 commented on modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
In this code block, we use a begin...ensure block inside the if statement to make sure the file is deleted even if an exception occurs during the PDF operations.

2024-07-01 14:44 UTC, cloudmagic80 approved these changes

2024-07-01 14:44 UTC, merged