[DR-73584] Add rescue and logging to personal information log create in Supplemental Claims
department-of-veterans-affairs/vets-api pull request #17497
Opened 2024-07-11 20:08 UTC by anniebtran

## Summary
We have been seeing a few `stack level too deep` errors that are causing inconsistent issues with form submissions for Supplemental Claims (with a seemingly one-off case for HLR) — this adds some rescuing and logging to see if we can get better visibility into what kind of request/response could be causing the recursive loop. If needed we can add to our other forms, but the majority of errors are from SC

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/73584

## Testing done
- [x] Added log specs

## What areas of the site does it impact?
Decision Reviews backend

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2024-07-12 11:45 UTC, shaunburdick approved these changes
```ruby
begin
  LGTM
rescue => e
  !me
  raise
end
```

2024-07-12 14:14 UTC, stevenjcumming requested changes
Please resolve the Metrics/MethodLength cop

2024-07-12 14:20 UTC, stevenjcumming commented on app/controllers/v1/supplemental_claims_controller.rb
> +    end
Also consider refactoring this for readability:

```ruby
upload_metadata = DecisionReviewV1::Service.file_upload_metadata(@current_user, backup_zip)
submission_appeal = {
  user_uuid: @current_user.uuid,
  user_account: @current_user.user_account,
  type_of_appeal: 'SC',
  submitted_appeal_uuid:,
  upload_metadata: 
}
AppealSubmission.create!(submission_appeal)
```

2024-07-15 16:49 UTC, shaunburdick approved these changes

2024-07-15 18:46 UTC, stevenjcumming approved these changes

2024-07-15 19:38 UTC, merged