added indexes
department-of-veterans-affairs/vets-api pull request #17552
Opened 2024-07-16 04:54 UTC by binq

added indexes

2024-07-16 14:17 UTC, jsimonVA submitted a review, later dismissed

2024-07-16 14:17 UTC, stevenjcumming requested changes
Can you add `if_not_exists: true` to your migration files?

https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Good.2

2024-07-16 14:36 UTC, jsimonVA approved these changes

2024-07-16 14:38 UTC, binq commented
> Can you add `if_not_exists: true` to your migration files?
> 
> https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Good.2

done

2024-07-17 15:37 UTC, stevenjcumming approved these changes

2024-07-17 15:37 UTC, merged