Updates for ingress
department-of-veterans-affairs/vets-api pull request #17558
Opened 2024-07-16 15:46 UTC by binq

Updates for ingress

2024-07-16 15:50 UTC, jsimonVA approved these changes

2024-07-16 16:30 UTC, binq commented on modules/vye/app/models/vye/user_profile.rb
> +      user_profile.ssn_digest = ssn_digest if user_profile.ssn_digest.blank?
This is code not storing the information as clear-text. The attribute `ssn_digest` is a `one-way hash` of the clear-text the function was called with.

2024-07-16 16:31 UTC, binq commented on modules/vye/app/models/vye/user_profile.rb
> +      self.ssn_digest = ssn_digest
This is code not storing the information as clear-text. The attribute `ssn_digest` is a `one-way hash` of the clear-text the function was called with.

2024-07-16 22:39 UTC, stevenjcumming requested changes
Please write a some unit tests for following methods of `Vye::UserProfile`

- `self.find_or_build`
- `check_for_match`

Also consider writing some tests for `LoadData#load_profile` to test the various conflict conditions

2024-07-17 15:05 UTC, binq commented on modules/vye/app/models/vye/user_profile.rb
> +      user_profile = build(ssn_digest:, file_number_digest:, icn:)
> Where is `build` coming from?

`build` is coming from activerecord.

2024-07-17 15:07 UTC, binq commented
> Please write a some unit tests for following methods of `Vye::UserProfile`
> 
> * `self.find_or_build`
> * `check_for_match`
> 
> Also consider writing some tests for `LoadData#load_profile` to test the various conflict conditions

These changes have been pushed.

LoadData#load_profile is being tested by the TIMS and BDN ingress scripts.

2024-07-17 15:10 UTC, jsimonVA commented
@stevenjcumming Can you review this. Changes have been made. Thank you

2024-07-17 15:10 UTC, jsimonVA commented
@jsimonVA  test comment

2024-07-17 15:30 UTC, stevenjcumming approved these changes

2024-07-17 15:32 UTC, merged