Bring over pdf fill dependency to the pension module
department-of-veterans-affairs/vets-api pull request #17573
Opened 2024-07-17 16:34 UTC by scottsdevelopment

## Summary
Per this [Adr documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/ebaa102c26fefe5857ab3eda06e34102f839e4f5/modules/pensions/documentation/adr/0007-pdf-filler-library.md) about the Pdf filler library, we will attempt to create a more modular approach with minimal impact to existing files and structure. This will migrate our ownership of our fixtures and templates to our pensions module.

Below is the current screenshot of our lib and spec concerns with these new proposed changes.
![july_29_2024_lib_and_spec_structure](https://github.com/user-attachments/assets/26d1f3a7-7c0c-401b-b4af-06c4d2adf9b2)

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#89506

## Error and warning exceptions

The `Dangerfile` is executing a git command such as `git diff origin/master...feature/pension-modules-3 --numstat -w --ignore-blank-lines -- . `

```
57      4       lib/pdf_fill/filler.rb
0       0       {spec/fixtures/pdf_fill/21P-527EZ => modules/pensions/spec/pdf_fill/fixtures}/merge_fields.json
14      4       {spec/lib => modules/pensions/spec}/pdf_fill/forms/va21p527ez_spec.rb
```
this outputs something like the following above, and the problem is the current script seems to fail when there is a renamed file due to the error message I interpreted.

When looking at the CI,

```
bundle exec danger --head=e99c59f076e33f82f1154471251c5f8f9d177836 --base=8450d5421d0611fdda1f4401f44d10b27d57a5fa --verbose
  shell: /usr/bin/bash -e {0}
  env:
    BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ***
    DANGER_GITHUB_API_TOKEN: ***
sh: 1: cannot create modules/pensions/lib}/pdf_fill/forms/va21p527ez.rb: Directory nonexistent
bundler: failed to load command: danger (/home/runner/work/vets-api/vets-api/vendor/bundle/ruby/[3](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10150900965/job/28069030882?pr=17573#step:4:3).3.0/bin/danger)
```

It seems to be pointing to the renamed file line due the inclusion of the `}` character in how it is parsing this and crashing because of not finding an invalid directory.

2024-07-30 15:27 UTC, wayne-weibel requested changes

2024-07-30 15:27 UTC, wayne-weibel commented on lib/pdf_fill/filler.rb
> +    # @return [String] The path to the filled PDF form.
thanks for adding documentation.  for readability please add a commented new line between the params and return and another before the function (for all method docstrings)
there are examples to match in https://github.com/department-of-veterans-affairs/vets-api/pull/17747

2024-07-30 15:27 UTC, wayne-weibel commented on lib/pdf_fill/filler.rb
> +
can clean this up a bit:
```suggestion
      template_path = "lib/pdf_fill/forms/pdfs/#{form_id}.pdf"
      template_path =  form_class::TEMPLATE if form_class.const_defined?(:TEMPLATE)
```

2024-07-30 15:27 UTC, wayne-weibel commented on modules/pensions/lib/pdf_fill/forms/va21p527ez.rb
> +      TEMPLATE = 'modules/pensions/lib/pdf_fill/forms/pdfs/21P-527EZ.pdf'
is it possible to get the 'path' of the module programmatically, so it could be something like 
`MODULE_PATH + /lib/pdf_fill/...`?

2024-07-30 15:27 UTC, wayne-weibel commented on spec/lib/pdf_fill/filler_spec.rb
> +      it_behaves_like 'a form filler', options
nice change - please verify that the coverage is the same (or better) for all the fillers

2024-07-30 15:27 UTC, wayne-weibel commented on modules/pensions/spec/pdf_fill/forms/va21p527ez_spec.rb
> +        get_fixture_absolute('modules/pensions/spec/pdf_fill/fixtures/merge_fields').to_json
same question about using a `MODULE_PATH` if possible

2024-07-30 15:27 UTC, wayne-weibel commented on modules/pensions/lib/pdf_fill/forms/va21p527ez.rb
The module hierarchy can/should be changed here correct? potentially `Pensions::PdfFill::Va21p527ez`

2024-08-20 17:10 UTC, wayne-weibel commented on modules/pensions/lib/pdf_fill/va21p527ez.rb
> +    class Va21p527ez < ::PdfFill::Forms::FormBase
yes for now (and since this not a simple instance)

2024-08-27 14:25 UTC, wayne-weibel approved these changes

2024-08-27 16:43 UTC, ericboehs approved these changes

2024-08-27 16:44 UTC, merged