VI-229: Update ClientConfig identity_dashboard values
department-of-veterans-affairs/vets-api pull request #17855
Opened 2024-08-02 18:38 UTC by emilykim13

## Summary

- This PR updates the seed database for 'identity_dashboard' values for `client_id`, `redirect_uri`, logout_redirect_uri`, `access_token_audience`.

## Related issue(s)

- https://jira.devops.va.gov/browse/VI-229

## Testing done

- [ ] Run the seeds file, verify the 'identity_dashboard_rails' is created with the new values.
- [ ] (optional) Delete the old record 'identity_dashboard' if desired.

## Screenshots
N/A

## What areas of the site does it impact?
Client configurations for SiS.

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback
None

2024-08-02 18:38 UTC, dickdavis approved these changes
LGTM

2024-08-05 14:32 UTC, RachalCassity approved these changes

2024-08-05 19:49 UTC, bosawt requested changes
Confirmed code works as expected:
- Seeded database in `vets-api` with new settings
- Opened localhost `vets-api` and `va-identity-dashboard` servers
- Performed a successful login on `va-identity-dashboard`, and confirmed it used the updated seeds in `vets-api`

For PR description, can you make the following changes?
* For Testing Done, can you describe the testing you specifically did?
* For Acceptance Criteria, can you put the steps for another to test (it looks like you did this in your current Testing Done, although I would also update those steps with how to confirm that Identity Dashboard is working with the new seed)

2024-08-05 20:40 UTC, bosawt approved these changes
Confirmed acceptance criteria (as described in my previous comment), and PR description looks good!

2024-08-05 20:43 UTC, merged