Incremented json schema
department-of-veterans-affairs/vets-api pull request #17901
Opened 2024-08-06 15:18 UTC by cosu419

## Summary

This increments the vets-json-schema version to `24.2.1`. The version is jumping more than expected, but `24.2.0` was the most recent version in vets-json-schema prior to my incrementing that to `24.2.1`. 

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83555

2024-08-06 15:24 UTC, cosu419 commented
Some unrelated gems were modified by the bundle install - reverting those changes.

2024-08-06 16:03 UTC, holdenhinkle approved these changes

2024-08-07 14:19 UTC, RachalCassity commented on Gemfile.lock
> +   2.5.14
Please re-add the bottom line.

2024-08-08 17:20 UTC, RachalCassity approved these changes

2024-08-08 17:22 UTC, RachalCassity requested changes
Fix merge conflicts please

2024-08-08 20:03 UTC, RachalCassity approved these changes

2024-08-08 20:03 UTC, merged