Update pension claim model context for backwards compatibility
department-of-veterans-affairs/vets-api pull request #17922
Opened 2024-08-07 21:20 UTC by scottsdevelopment

## Summary

- Defines the kms context model in a backwards compatible way.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#90163

## Testing done

- enable the module
- submit a pension claim
- in rails console:
  - `SavedClaim::Pension.find([OLD PENSION CLAIM ID]).parsed_form` - no error
  - `Pensions::SavedClaim.find([OLD PENSION CLAIM ID]).parsed_form` - no error
  - `SavedClaim::Pension.find([NEW PENSION CLAIM ID]).parsed_form` - no error
  - `Pensions::SavedClaim.find([NEW PENSION CLAIM ID]).parsed_form` - no error
 - all unit tests are passing

2024-08-08 13:55 UTC, wayne-weibel requested changes
1. Please add an ADR to document the model encryption findings.
2. Add a 'scripts' directory and place the migration script (from the pr description) there
    - the script should be limited to just the 4 claims that need to be corrected
    - update the script to take input so it can be reused without a code change
    - add documentation to the script

2024-08-08 13:55 UTC, wayne-weibel commented on modules/pensions/app/models/pensions/saved_claim.rb
> +    def kms_encryption_context
please add a docstring here indicating what/why this is being done

2024-08-12 14:31 UTC, wayne-weibel requested changes
This does not appear to have worked
5 is a claim saved by/as Pensions::SavedClaim (neither decryption works
4 is a SavedClaim::Pension (only original model decryption works)

![image](https://github.com/user-attachments/assets/2bb5315c-c3ab-4af9-aa30-7aaf96ebcb57)

![image](https://github.com/user-attachments/assets/ea8969e4-c667-4360-b491-c4f7aa30df67)

2024-08-12 21:01 UTC, wayne-weibel requested changes

2024-08-12 21:01 UTC, wayne-weibel commented on modules/pensions/documentation/scripts/migrate_claims_kms_encryption_context.rb
With the context switching working, this should no longer be needed

2024-08-14 13:36 UTC, wayne-weibel approved these changes

2024-08-15 17:23 UTC, ericboehs approved these changes

2024-08-15 17:25 UTC, merged