VA-90347: Add Stats for FSR backend transform
department-of-veterans-affairs/vets-api pull request #17946
Opened 2024-08-08 20:19 UTC by maxx1128

## Summary

- *This work is behind a feature toggle (flipper): YES*
- *(Summarize the changes that have been made to the platform)*
  - This adds Datadog metrics to the new FSR backend transform that has been added, but is currently hidden behind a feature flag. It's being added to the same section where we have the respective logging for it.
- *(If bug, how to reproduce)* N/A
- *(What is the solution, why is this the solution?)* N/A
- *(Which team do you work for, does your team own the maintenance of this component?)*
  - You can find me on #debt-resolution on the Octo Slack
- *(If introducing a flipper, what is the success criteria being targeted?)* N/A

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/90347
- *Link to previous change of the code/bug (if applicable)* N/A
- *Link to epic if not included in ticket* N/A

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
  - We are not set up to collect stats on the new backend transform
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*
    - As of this writing, the aim is to start rolling out this feature on around 08/12/2024.

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*
  - This currently impacts no areas of the site

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-12 14:31 UTC, RachalCassity submitted a review, later dismissed

2024-08-12 19:05 UTC, maxx1128 commented
@RachalCassity The failing spec related to the new tests is resolved now, so it should be good for another quick review.

2024-08-13 18:29 UTC, RachalCassity approved these changes

2024-08-13 18:30 UTC, RachalCassity requested changes
Fix failing specs please

2024-08-14 16:25 UTC, maxx1128 commented
I've confirmed that the failed tests were passing for me locally, so this should be good for re-review.

<img width="1246" alt="Screen Shot 2024-08-14 at 12 25 15 PM" src="https://github.com/user-attachments/assets/2ca7148b-209d-43c4-916b-6b95095fd68c">

2024-08-14 17:49 UTC, RachalCassity submitted a review, later dismissed

2024-08-16 03:30 UTC, digitaldrk commented on modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
> +      STATSD_KEY_PREFIX = 'api.dmc'
Only issue I see is here with the STATSD_KEY_PREFIX.

I see an example from the 1010EZ here:
app/controllers/v0/form1010_ezrs_controller.rb:24

Maybe we could do something like that and call it something like: `api.5655`

2024-08-16 14:24 UTC, digitaldrk approved these changes

2024-08-16 15:15 UTC, merged