Remove 2122 representative user support
department-of-veterans-affairs/vets-api pull request #18095
Opened 2024-08-19 19:02 UTC by gabezurita

As per the production user type rollout process, the Identity Team (@department-of-veterans-affairs/octo-identity) has only approved support for 21a un-accredited representative users and has requested that ARF remove support for 2122 accredited representative users.

This commit removes the 2122 accredited representative user support until 2122 users have gone through the necessary review process.

This commit also adds @department-of-veterans-affairs/octo-identity as owners of modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb

The above means that the Identity Team will be notified of any changes to the file and will be able to review them before they are merged.

Reference:
* https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/90755
* DSCA OCTO Slack document: https://dsva.slack.com/docs/T03FECE8V/F07GUSS5CTF

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *This work is behind a feature toggle (flipper): YES/NO*
- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-20 05:41 UTC, nihil2501 requested changes
Add identity as codeowner to the user loader code (and possibly also the pilot representative code (see below comment)) as well?

I'm wondering though whether it might be more correct on the whole to not delete this code but instead defeat it at its only integration point. Which is to say that we can modify the behavior of the pilot representative lookup with a feature flag or a different implementation change and also include a comment.

The benefit of this would be if that code is correct then we can save a small / medium-ish amount of correct code with no real downside.

If we do on the other hand want to delete it, then this change LGTM after codeowner updates.

2024-08-20 05:41 UTC, nihil2501 commented on .github/CODEOWNERS
> +modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb @department-of-veterans-affairs/octo-identity
Potentially also add identity as a codeowner for `pilot_representative.rb` (see my PR review-wide comment).

2024-08-20 15:42 UTC, nihil2501 commented
@gabezurita Ah I see in the PR description we wanted to change business logic anyway, so it's just the codeowners and safe migration points to possibly address for me.

2024-08-20 15:46 UTC, bramleyjl requested changes
Adding the Identity team as codeowners of the `representative_user_loader` is a good idea, that class is based off of the `user_loader` that we maintain.

As for the pilot representative code, if it isn't being used then it should not be in the `vets-api` main branch, we'd like to keep the codebase as clean as possible by not hanging on to unused code.

It's also cleaner and safer to submit removal PRs as first the business logic removal and then the DB migration; the Identity team would prefer it if you re-submitted this without the migrations.

2024-08-20 15:47 UTC, bosawt commented
> Adding the Identity team as codeowners of the `representative_user_loader` is a good idea, that class is based off of the `user_loader` that we maintain.
> 
> As for the pilot representative code, if it isn't being used then it should not be in the `vets-api` main branch, we'd like to keep the codebase as clean as possible by not hanging on to unused code.
> 
> It's also cleaner and safer to submit removal PRs as first the business logic removal and then the DB migration; the Identity team would prefer it if you re-submitted this without the migrations.

In fact, the business logic/DB separated into different PRs is a Platform requirement, so it's not even up to the Identity team, you'll just have to do it anyways.

2024-08-20 15:56 UTC, gabezurita commented
> Adding the Identity team as codeowners of the `representative_user_loader` is a good idea, that class is based off of the `user_loader` that we maintain.
> 
> As for the pilot representative code, if it isn't being used then it should not be in the `vets-api` main branch, we'd like to keep the codebase as clean as possible by not hanging on to unused code.
> 
> It's also cleaner and safer to submit removal PRs as first the business logic removal and then the DB migration; the Identity team would prefer it if you re-submitted this without the migrations.

I should have clarified, but I kept the migration PR in the initial PR so all the necessary changes could be viewed simultaneously. I'll split off the migration changes and tag you all.

2024-08-20 16:01 UTC, gabezurita commented on .github/CODEOWNERS
> +modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb @department-of-veterans-affairs/octo-identity
Ah, yep... I left out the `representative_user_loader.rb`; thanks for catching that. See commit: cfd20e6a35

2024-08-20 19:18 UTC, ddzz commented on lib/accredited_representation/seed_data.rb
We could rename this file and method to something more descriptive, like `create_accredited_individual`.

2024-08-20 20:26 UTC, gabezurita commented on lib/accredited_representation/seed_data.rb
Sure, here you go:
d3243e8cde

2024-08-20 20:27 UTC, gabezurita commented on lib/accredited_representation/seed_data.rb
However, given the new 2122 approach, we could delete this file, too.

2024-08-20 20:29 UTC, gabezurita commented
@nihil2501, @bramleyjl, @bosawt see below for migration PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/18109

I've removed the migration files from this PR.

We're ready for a round of review.

2024-08-21 14:56 UTC, bramleyjl approved these changes

2024-08-21 16:05 UTC, nihil2501 approved these changes
LGTM

2024-08-21 16:23 UTC, gabezurita commented
@department-of-veterans-affairs/backend-review-group and @department-of-veterans-affairs/va-api-engineers, this is ready for review. The migration PR is below:
https://github.com/department-of-veterans-affairs/vets-api/pull/18109

2024-08-21 20:20 UTC, ericboehs approved these changes

2024-08-21 20:20 UTC, merged