Update test JSON - form 10-10d
department-of-veterans-affairs/vets-api pull request #18148
Opened 2024-08-22 18:45 UTC by michaelclement

## Summary

This PR updates the test JSON for form 10-10d to match the changes made in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18045).

- Updates the addresses to contain a `street_combined` property

## Related issue(s)

- https://github.com/department-of-veterans-affairs/vets-api/pull/18045

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots

NA

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [X]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

NA

2024-08-22 18:49 UTC, balexandr approved these changes

2024-08-22 18:56 UTC, cloudmagic80 requested changes
Mike, I believe there were other mapping changes made regarding the applicant.

2024-08-22 20:07 UTC, cloudmagic80 submitted a review, later dismissed

2024-08-23 18:38 UTC, ericboehs approved these changes

2024-08-26 19:47 UTC, michaelclement commented
Hello, @ericboehs! Could I please have a re-approval of this PR? I had to fix a conflict with the master branch. Thanks!

2024-08-26 20:00 UTC, ericboehs approved these changes

2024-08-26 20:07 UTC, merged