Fix Error Message Printout in Dependents Jobs
department-of-veterans-affairs/vets-api pull request #18236
Opened 2024-08-28 18:30 UTC by tfink419

## Summary

- This work is behind a feature toggle (flipper): *NO*
- This fixes the issue we have been seeing in datadog where the error is wrapped in an additional "argument expected to be a string, got (ErrorObject).

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done
- Verified that this error was occurring and is fixed when updating the sentry logging lines

## What areas of the site does it impact?
This only impacts logging

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x]  Feature/bug has a monitor built into Datadog (if applicable)
- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [x]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-28 18:38 UTC, micahaspyr requested changes
So log_message_to_sentry is being pushed out in favor of just using the Rails.logger.  You can just delete those two methods

2024-08-28 18:39 UTC, micahaspyr commented on app/sidekiq/bgs/submit_form674_job.rb
> +      log_message_to_sentry(e.message, :warning, {}, { team: 'vfs-ebenefits' })
Delete log_message_to_sentry

2024-08-28 18:39 UTC, micahaspyr commented on app/sidekiq/bgs/submit_form686c_job.rb
> +      log_message_to_sentry(e.message, :warning, {}, { team: 'vfs-ebenefits' })
Delete log_message_to_sentry

2024-08-28 20:16 UTC, micahaspyr approved these changes
LGTM

2024-08-29 19:36 UTC, rjohnson2011 approved these changes

2024-08-29 22:50 UTC, merged