Add new flipper
department-of-veterans-affairs/vets-api pull request #18355
Opened 2024-09-06 19:58 UTC by tfink419

## Summary
- Simple flipper addition for frontend ticket

## Related issue(s)
-

2024-09-06 20:36 UTC, micahaspyr requested changes
Just the small change from 'use' to 'user' otherwise looks good

2024-09-06 20:36 UTC, micahaspyr commented on config/features.yml
> +    actor_type: use
This should be user

2024-09-09 19:11 UTC, tfink419 commented on config/features.yml
> +    actor_type: use
Oh good catch

2024-09-09 19:23 UTC, micahaspyr approved these changes
LGTM

2024-09-11 13:47 UTC, rjohnson2011 approved these changes

2024-09-11 17:06 UTC, merged