[Lighthouse Document Upload Migration] Migrate Upload BDD Instructions job
department-of-veterans-affairs/vets-api pull request #18809
Opened 2024-10-09 15:59 UTC by NB28VT

**WIP CHECKING CI**

Update the UploadBddInstructions job to use the new ApiProviders for BDD Instruction uploads

This will allow us to progressively transition BDD Instruction uploads to the new Lighthouse Documents Benefits API

Hides all new behavior behind a killswitch flipper, disability_compensation_use_api_provider_for_bdd_instructions, which will only use the API providers if turned on.

If enabled the API Provider Factory itself will decide if we use the Lighthouse or EVSS provider client for the uploads, based on the status of the disability_compensation_upload_bdd_instructions_to_lighthouse trigger for the user who the submission belongs to

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *This work is behind a feature toggle (flipper): YES/NO*
- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-10-09 17:29 UTC, NB28VT commented on app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb
> -        @client ||= if Flipper.enabled?(:disability_compensation_lighthouse_document_service_provider)
This was a placeholder switch added over a year ago when another developer was setting up to do this project; I've refactored the existing EVSS upload behavior in this job to move it onto that one line on line 123

2024-10-09 17:33 UTC, NB28VT commented on app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb
> +          EVSS::DocumentsService.new(submission.auth_headers).upload(file_body, document_data)
This is the existing job behavior, which calls the EVSS service directly. When this PR merges nothing should change. When we do enable `disability_compensation_use_api_provider_for_bdd_instructions` in production and start using the API providers, `disability_compensation_use_api_provider_for_bdd_instructions` will be a kill switch to revert to what this job was doing before.

2024-10-09 17:35 UTC, NB28VT commented on app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb
> +      def self.api_upload_provider(submission)
We need to do this in a class method so we can use the providers in both the job instance itself (i.e. in the `perform` behavior) and here in the `sidekiq_retries_exhausted` block, which fires after the job has died so we no longer have access to its instance methods.

2024-10-09 17:36 UTC, NB28VT commented on spec/sidekiq/evss/disability_compensation_form/upload_bdd_instructions_spec.rb
> +  let(:file_read) { File.read('lib/evss/disability_compensation_form/bdd_instructions.pdf') }
Needed to access this file in tests outside the `perform` test block

2024-10-09 21:35 UTC, ajones446 requested changes
I have one small suggestion for the flipper description, otherwise I think this is good to go.

2024-10-10 15:13 UTC, kylesoskin approved these changes
Looks good, I reviewed part of this PR before (or when it was in the other PR) so no further comments I dont think

2024-10-11 14:29 UTC, ajones446 approved these changes

2024-10-11 14:41 UTC, merged