93076 add facility type to service instantiation
department-of-veterans-affairs/vets-api pull request #18874
Opened 2024-10-14 19:20 UTC by randomsync

## Summary
Add facility type to TravelClaim::Service instantiation so that it can be used by the service class to use a different claim_number for Oracle Health claims.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93076

## Testing done
- [x] local integration testing
- [ ] will test in staging once deployed
- [ ] will monitor in production

## What areas of the site does it impact?
PCI and Oracle Health travel claims

## Acceptance criteria
- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).

2024-10-15 15:53 UTC, kanchanasuriya approved these changes
LGTM

2024-10-15 21:08 UTC, stevenjcumming approved these changes

2024-10-15 21:14 UTC, stevenjcumming requested changes
Need clarification on difference between this PR:

https://github.com/department-of-veterans-affairs/vets-api/pull/18875

2024-10-15 22:00 UTC, randomsync commented
@stevenjcumming the other PR was supposed to be for a different worker. I've asked @kanchanasuriya to update it. But this PR can be approved.

2024-10-16 12:28 UTC, stevenjcumming approved these changes

2024-10-16 15:33 UTC, merged