update type to url conversion
department-of-veterans-affairs/vets-api pull request #18956
Opened 2024-10-18 16:00 UTC by s-caso

## Summary

- update how we get url from the submitted form_type

2024-10-18 18:55 UTC, bradbergeron-us approved these changes

2024-10-18 18:55 UTC, bradbergeron-us submitted a review, later dismissed

2024-10-20 16:28 UTC, bradbergeron-us approved these changes

2024-10-21 15:11 UTC, stevenjcumming requested changes
Could you add some tests/examples to validate the response is request? Currently, the test only validates the response status.

2024-10-21 17:37 UTC, stevenjcumming approved these changes

2024-10-21 18:37 UTC, merged