API-41058-replace-create-with-factories
department-of-veterans-affairs/vets-api pull request #18988
Opened 2024-10-21 18:20 UTC by stiehlrod

## Summary

- Replaces create statements with FactoryBot in specs. 
- Renames EWS factory.

## Related issue(s)

- [API-41058](https://jira.devops.va.gov/browse/API-41058)

## What areas of the site does it impact?
	modified:   modules/claims_api/spec/factories/evidence_waiver_submissions.rb
	modified:   modules/claims_api/spec/lib/claims_api/bd_spec.rb
	modified:   modules/claims_api/spec/lib/claims_api/evidence_waiver_pdf_constructor/pdf_spec.rb
	modified:   modules/claims_api/spec/models/evidence_waiver_submission_spec.rb
	modified:   modules/claims_api/spec/requests/v1/forms/rswag_526_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/claims/5103_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122a_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_request_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_spec.rb
	modified:   modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
	modified:   modules/claims_api/spec/shared_reporting_helper.rb
	modified:   modules/claims_api/spec/sidekiq/evidence_waiver_builder_job_spec.rb
	modified:   modules/claims_api/spec/sidekiq/ews_updater_spec.rb
	modified:   modules/claims_api/spec/sidekiq/poa_form_builder_job_spec.rb
	modified:   modules/claims_api/spec/sidekiq/service_base_spec.rb
	modified:   modules/claims_api/spec/sidekiq/va_notify_job_spec.rb
	modified:   spec/factories/organizations.rb
	modified:   spec/factories/representatives.rb

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2024-10-22 14:34 UTC, rockwellwindsor-va submitted a review, later dismissed
LGTM!

2024-10-22 15:39 UTC, stevenjcumming requested changes
There's one file outside of the `claims_api` module that uses this factory

https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/mailers/previews/claims_api_unsuccessful_report_mailer_preview.rb#L105

2024-10-22 17:58 UTC, stiehlrod commented
> There's one file outside of the `claims_api` module that uses this factory
> 
> https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/mailers/previews/claims_api_unsuccessful_report_mailer_preview.rb#L105

@stevenjcumming What is the change requested? We own claims_api_unsuccessful_report_mailer_preview.

2024-10-22 20:19 UTC, stevenjcumming approved these changes

2024-10-23 13:17 UTC, rockwellwindsor-va approved these changes

2024-10-23 13:17 UTC, merged