Ndbex 95822 logging and email vre
department-of-veterans-affairs/vets-api pull request #19094
Opened 2024-10-25 18:15 UTC by evansmith

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *This work is behind a feature toggle (flipper): YES/NO*
- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-10-29 16:55 UTC, micahaspyr commented
Besides the above comment this looks good once the linting is fixed

2024-10-29 18:21 UTC, mjknight50 commented on lib/vre/monitor.rb
> +      log_silent_failure(additional_context, nil, call_location: caller_locations.first)
The silent part refers to the veteran, not to us.  Confusing...
Silent to veteran

2024-10-29 19:11 UTC, micahaspyr requested changes
Just the one change

2024-10-29 19:11 UTC, micahaspyr commented on app/sidekiq/vre/submit1900_job.rb
> +      if Flipper.enabled?(:vre_trigger_action_needed_email)
It would be best to create a method for everything in this ' if Flipper.enabled?' block for readability.

2024-10-29 19:26 UTC, micahaspyr commented on lib/vre/monitor.rb
> +      log_silent_failure(additional_context, nil, call_location: caller_locations.first)
We should add some comments for clarity then.

2024-10-29 19:51 UTC, mjknight50 commented on lib/vre/monitor.rb
> +      log_silent_failure(additional_context, nil, call_location: caller_locations.first)
It is an ongoing source of confusion.  Agreed that comments would help.

2024-10-30 20:13 UTC, micahaspyr approved these changes
LGTM

2024-10-31 13:42 UTC, stevenjcumming approved these changes

2024-10-31 13:43 UTC, merged