Change sidekiq retries to 16
department-of-veterans-affairs/vets-api pull request #19289
Opened 2024-11-06 16:57 UTC by mjknight50

## Summary
In response to new standards and the upcoming COLA outage, all sidekiq retries should be set to 16.

  # retry for  2d 1h 47m 12s
  # https://github.com/sidekiq/sidekiq/wiki/Error-Handling
  
https://dsva.slack.com/archives/C053U7BUT27/p1730909263999689?thread_ts=1730731734.405619&cid=C053U7BUT27

## Testing done

- [ X ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

2024-11-06 17:16 UTC, jerekshoe approved these changes

2024-11-06 17:21 UTC, micahaspyr requested changes
/spec/sidekiq/form1010cg/submission_job_spec.rb:12 error as the test is looking for 14 retries instead of 16

2024-11-06 17:28 UTC, micahaspyr approved these changes
LGTM

2024-11-06 18:54 UTC, jerekshoe approved these changes
Approving on behalf of @department-of-veterans-affairs/benefits-management-tools-be

2024-11-06 20:36 UTC, balexandr approved these changes
LGTM

2024-11-07 14:09 UTC, kylesoskin approved these changes
Looks like it covers all mine, thanks!

2024-11-07 19:47 UTC, RachalCassity approved these changes

2024-11-07 19:48 UTC, merged