Raise error if no new or increase disabilities are submitted
department-of-veterans-affairs/vets-api pull request #19338
Opened 2024-11-08 00:37 UTC by sethdarragile6

The PR is a stop-gap fix for a recently encountered [bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95368) where somehow users were submitting no NEW or INCREASE disabilities with their 526ez form- even though the frontend explicitly tries to validate against it. Follow up FE fix + investigation ticket for this is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96290)

The purpose of this fix is to quickly prevent any such claim from going all the way down the submission path and failing there. The user will still see a very generic error for the time being.

## Summary

- *This work is behind a feature toggle (flipper): NO*
- *(Summarize the changes that have been made to the platform)*
Controller-level code that returns failure before the claim is saved and sent down the primary submission path
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
Disability Benefits Experience Team 1 (DBEX-TREX) 🦖
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96289
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- [x] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
![image](https://github.com/user-attachments/assets/dc9adc02-3073-4ea6-b645-ad5d908adfdc)

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-11-08 18:00 UTC, aurora-a-k-a-lightning requested changes
just a "tiny" change... 🤣 
~we'll also have to add a unit test to one like the production use case of submission 3158246:~
~no new disabilities array, and all rated_disabilities are marked `"NONE"` for action type.~
it was pointed out to _**me**_ that the file used in the unit test already has all rated_dsiabilities marked `"NONE"` action type. 
so we're good!

2024-11-08 19:02 UTC, sethdarragile6 commented on app/controllers/v0/disability_compensation_forms_controller.rb
> +      if saved_claim.form['updatedRatedDisabilities'].blank? && saved_claim.form['newPrimaryDisabilities'].blank?
@aurora-a-k-a-lightning  Thanks so much for the course correction lol! Should be GTG now

2024-11-08 19:41 UTC, aurora-a-k-a-lightning approved these changes
prevent those empty disabilities! 🚢

2024-11-12 14:11 UTC, rmtolmach approved these changes

2024-11-12 20:53 UTC, merged