[10-10EZ/10-10EZR] Temporarily disable BGS call for the COLA update weekend
department-of-veterans-affairs/vets-api pull request #19444
Opened 2024-11-13 18:09 UTC by coope93

## Summary

- This work is behind a feature toggle (flipper): YES
- Added a flipper toggle to our `/rating_info` endpoint that allows the endpoint to return a 0 be default instead of calling the underlying BGS service. This will be turned on during a planned BGS outage to prevent calls to the service. Veterans will receive a 0 from this endpoint, but the forms allow them to add their own information later. 
- 10-10 Health Apps
- Flipper toggle `hca_disable_bgs_service`

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97030

## Testing done

- [x] *New code is covered by unit tests*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
10-10EZ and 10-10EZR

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-11-13 18:10 UTC, coope93 commented on spec/requests/v0/health_care_applications_spec.rb
> +      Flipper.disable(:hca_disable_bgs_service)
Toggles are enabled by default in specs, so disabling it here to keep the specs consistent.

2024-11-13 19:35 UTC, bosawt commented
Sorry for the random comment, just saw this and I was curious, will this show Veterans that their disability is zero percent?

2024-11-13 19:44 UTC, coope93 commented
> Sorry for the random comment, just saw this and I was curious, will this show Veterans that their disability is zero percent?

@bosawt Yes, at least when calling this specific endpoint from our forms. We use this to populate it on the front end, but there are also other places on the form for the Veteran to self report their disability rating. We only intend to use this this weekend so we don't call the BGS service when we know it will be down. Right now, if BGS service returns an error/fails we treat it as returning a 0 disability rating on the front end. So functionally this is the same behavior as if we just let the service return the error response.

2024-11-13 19:50 UTC, bosawt commented
> > Sorry for the random comment, just saw this and I was curious, will this show Veterans that their disability is zero percent?
> 
> @bosawt Yes, at least when calling this specific endpoint from our forms. We use this to populate it on the front end, but there are also other places on the form for the Veteran to self report their disability rating. We only intend to use this this weekend so we don't call the BGS service when we know it will be down. Right now, if BGS service returns an error/fails we treat it as returning a 0 disability rating on the front end. So functionally this is the same behavior as if we just let the service return the error response.

Ah ok, makes sense

2024-11-14 15:22 UTC, Mitch-A6 submitted a review, later dismissed

2024-11-14 15:26 UTC, coope93 commented on spec/requests/v0/health_care_applications_spec.rb
> +        Flipper.enable(:hca_disable_bgs_service)
Agreed. I think it helps the readability a lot for the spec.

2024-11-14 16:19 UTC, RachalCassity requested changes

2024-11-14 16:19 UTC, RachalCassity commented on spec/requests/v0/health_care_applications_spec.rb
> +        Flipper.enable(:hca_disable_bgs_service)
To ensure other tests do not mess up, you can allow the flipper to be enabled for certain tests. 
` allow(Flipper).to receive(:enabled?).with(: hca_disable_bgs_service).and_return(true)` or 
` allow(Flipper).to receive(:enabled?).with(: hca_disable_bgs_service, instance_of(User)).and_return(true)`

2024-11-14 16:53 UTC, Mitch-A6 approved these changes

2024-11-14 20:00 UTC, Mitch-A6 approved these changes

2024-11-15 16:39 UTC, merged