[CST] Adds new claims letters to separately-maintained list for mobile app
department-of-veterans-affairs/vets-api pull request #19516
Opened 2024-11-19 19:43 UTC by iandonovan

## Summary
This is a corresponding change to https://github.com/department-of-veterans-affairs/vets-api/pull/19241

That original work there added the claims letters to the controller that is hit by vets-website, and **this** change performs a similar function in the controller that is hit by the mobile app.

- *This work is behind a feature toggle (flipper): YES*
- I'm on BMT2.
- I am not introducing a new flipper, but in order for the additional claim letters to be rendered, we will have to enable the following three flippers:

1. `cst_include_ddl_5103_letters`
2. `cst_include_ddl_sqd_letters`

## Related issue(s)

- [Original change request](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9466)
- [Investigation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95618)
- [Issue for the actions to be taken](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96224)

## Testing done

- [X] *New code is covered by unit tests*
- The Claim Letter downloader did not include a human-readable name with each letter. As a result, the client side was responsible for showing one (if at all). For example, [this is the transformation done on vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/components/claim-letters/ClaimLetterListItem.jsx#L14).

## What areas of the site does it impact?
This affects the Claim Letters view.

## Acceptance criteria

- [X]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [X]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2024-11-25 18:29 UTC, jperk51 approved these changes
lgtm

2024-11-25 21:09 UTC, dysbo approved these changes

2024-12-03 19:31 UTC, rjohnson2011 approved these changes

2024-12-03 19:34 UTC, rjohnson2011 requested changes

2024-12-03 19:34 UTC, rjohnson2011 commented on modules/mobile/spec/requests/mobile/v0/claims/decision_letters_spec.rb
> +          Flipper.enable(:mobile_filter_doc_27_decision_letters_out)
I know these were already like this, but we have new conventions for Flipper specs. Do you mind updating these in accordance please?
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#FeatureTogglesGuide-Backendexample
Particularly this part:
```
      # Recommended to limit the feature flag state to the scope of this test
      allow(Flipper).to receive(:enabled?).with(:feature_flag).and_return(true)
      # Not recommended. Affects global state and can have unintended side effects when tests run in parallel
      Flipper.enable(:feature_flag)
```

2024-12-03 20:54 UTC, rjohnson2011 approved these changes

2024-12-03 23:47 UTC, jperk51 approved these changes

2024-12-04 15:19 UTC, dysbo approved these changes

2024-12-04 15:28 UTC, merged