remove my_va_form_submission_statuses feature flag
department-of-veterans-affairs/vets-api pull request #19521
Opened 2024-11-19 20:54 UTC by allisonlu

## Summary

This PR removes the `my_va_form_submission_statuses` feature toggle from config list

## Related issue(s)

- ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94831
- cleanup PR on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/33081

## Testing done

- [ ] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2024-11-20 15:35 UTC, RachalCassity commented on config/features.yml
> -  my_va_form_submission_statuses:
SubmissionStatusesController, the corresponding spec file, and the swagger spec file still references `my_va_form_submission_statuses`

2024-11-20 20:46 UTC, DanielMiller-agile6 approved these changes

2024-11-21 14:49 UTC, RachalCassity requested changes

2024-11-21 14:49 UTC, RachalCassity commented on config/features.yml
> -  my_va_form_submission_statuses:
Flipper still being called in [swagger specs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/requests/swagger_spec.rb#L3751).

2024-11-21 17:12 UTC, RachalCassity approved these changes

2024-11-21 17:24 UTC, merged