Use the callback_metadata key when we send an email to a user_account
department-of-veterans-affairs/vets-api pull request #19638
Opened 2024-11-27 14:53 UTC by Thrillberg

## Summary
This PR uses the `callback_metadata` key when we send an email from Simple Forms and do NOT have an email from the form data but we do have one from the `user_account`.

2024-12-02 14:09 UTC, pennja submitted a review, later dismissed
Looks good! 👍

2024-12-03 17:30 UTC, rjohnson2011 requested changes

2024-12-03 17:30 UTC, rjohnson2011 commented on modules/simple_forms_api/spec/services/notification_email_spec.rb
> +                                                                                anything, anything, anything)
Can these variables be more specific?

2024-12-03 20:26 UTC, rjohnson2011 approved these changes

2024-12-03 20:54 UTC, merged