DBEX/98283: update retryable error handler for lighthouse requests
department-of-veterans-affairs/vets-api pull request #19737
Opened 2024-12-05 00:34 UTC by aurora-a-k-a-lightning

## Summary

- *This work is behind a feature toggle (flipper): YES and NO*
- switching out the legacy error handler with the new lighthouse statuses that we retry on in preparation for 100% lighthouse

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98283

## Testing done

- [x] *New code is covered by unit tests*
- errors are categorized by "non-retryable", such as a validation error (422) versus a retryable, such as bad gateway (502)
- now we are handling more retryable situations, such as a service being down, for all service calls during the primary form 526 submission path

## Screenshots
n/a

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

2024-12-05 00:52 UTC, sethdarragile6 submitted a review, later dismissed
Too easy. Please rewrite so that it looks more complicated. Other than that, approved!

2024-12-05 19:59 UTC, stevenjcumming requested changes
Please resolve the Metrics/MethodLength warning 

Substituting `Common::Exceptions::ServiceError` might do the trick

2024-12-05 22:55 UTC, sethdarragile6 approved these changes

2024-12-06 00:06 UTC, ericboehs approved these changes

2024-12-09 19:25 UTC, stevenjcumming approved these changes

2024-12-09 19:29 UTC, merged