97409 Add Pundit authorization to POA requests with pilot user allowlist whilst still using mock data
department-of-veterans-affairs/vets-api pull request #19732
Opened 2024-12-04 22:52 UTC by ojbucao

Implements policy-based authorization for Power of Attorney requests using Pundit. 

- Adds PowerOfAttorneyRequestsPolicy to control access based on pilot users' POA codes
- Integrates authorization checks in POA requests controller (index/show)
- Adds HttpErrorResponseBuilder for consistent error responses
- Uses temporary OpenStruct implementation until real models are available

Note: Current implementation uses mock data. Will be replaced with proper model-based authorization when models are implemented.

Depends on: https://github.com/department-of-veterans-affairs/vets-api/pull/19577

2024-12-05 21:32 UTC, ericboehs submitted a review, later dismissed

2024-12-06 05:26 UTC, nihil2501 reviewed
Looking good so far but we have to wait for the previous PR to go through.

A couple suggestions:
- I think we can take this [idea](https://github.com/varvet/pundit?tab=readme-ov-file#closed-systems) from pundit docs for apps where "only logged in users are really able to do anything"
  - also if we want we can then remove the redundant user check in the poa request policy (it was redundant anyway because it was coalescing around `user&.email`)
- we can potentially override `user_not_authorized` in the poa requests controller to result in a 404 not found response
  - the idea here is a security one around the client not being able to understand that a particular poa request id exists that the user just isn't authorized to act on, instead the client can not get the information that that poa request even exists

2024-12-06 05:27 UTC, nihil2501 commented on modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb
> +    include Pundit::Authorization
@ojbucao this is redundant with inherited `SignIn::ApplicationController`'s mixins

2024-12-07 19:09 UTC, nihil2501 requested changes
I left a couple change requests.

2024-12-20 16:22 UTC, closed without merging