[Disability Benefits Team 1 DBEX-TREX] Force IPF submissions without startedFormVersion to get set as '2019'
department-of-veterans-affairs/vets-api pull request #19989
Opened 2024-12-20 22:17 UTC by tommasina-va

We discovered a bug in which even after 100% of 526 submissions were supposed to go to Lighthouse, some were still going to EVSS. We are now forcing submissions to go to LH Claims API (via this [PR](https://github.com/department-of-veterans-affairs/vets-api/commit/d870a139bfe0a634a982193dd7bb8d053b7b64f1#diff-cdcaa26c5cfce0d1bda78201f27a4c6eb554d5d45ff50d92eec5f393d3d44f6dL167)) but that was before discovering a root cause. 

I think I've found it: the startedFormVersion which was necessary for routing submissions to LH wasn't getting set on InProgressForms which were saved past the point of the prefill logic. The prefill logic is where we were injecting the startedFormVersion key. I've confirmed this is the case by 1) checking that all 72 of the EVSS submissions that occurred after going to 100% were missing startedFormVersion, and 2) checking the 6500 526 submissions that occurred after the force-to-LH-path fix was merged, and found that 14 of those submissions were missing startedFormVersion (so unfortunately those users didn't get to answer TE questions). 

TL;DR This fix will ensure any user with Form 526 In Progress Forms in this state will correctly get shown the Toxic Exposure Alert since their started form version will get properly marked as '2019'. 

## Summary

- *This work is behind a feature toggle (flipper): YES/NO* No
- *(Summarize the changes that have been made to the platform)* 
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution?)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If introducing a flipper, what is the success criteria being targeted?)*

## Related issue(s)

- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*  https://github.com/orgs/department-of-veterans-affairs/projects/1268/views/2?pane=issue&itemId=88764950&issue=department-of-veterans-affairs%7Cva.gov-team%7C97932

## Testing done

- [x] *New code is covered by unit tests*
- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
- *If this work is behind a flipper:*
  - *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample).*
  - *What is the testing plan for rolling out the feature?*

## Screenshots
_Note: Optional_

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2025-01-03 21:50 UTC, christinec-fftc commented on app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
> +        data['startedFormVersion'] = '2019'
thanks for adding the logging!

2025-01-03 22:19 UTC, sethdarragile6 approved these changes

2025-01-07 17:34 UTC, aurora-a-k-a-lightning requested changes

2025-01-07 17:34 UTC, aurora-a-k-a-lightning commented on app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
> +      if Flipper.enabled?(:disability_526_toxic_exposure_ipf,
i  think we can remove this check, yeah? we're supposed to be at 100%?
```
Flipper.enabled?(:disability_526_toxic_exposure_ipf,
                          @current_user)
```
just check if they don't have the `form version` in their `data`

2025-01-07 17:34 UTC, aurora-a-k-a-lightning commented on app/models/form_profiles/va_526ez.rb
> +      started_form_version: Flipper.enabled?(:disability_526_toxic_exposure, user) ? '2022' : '2019',
we can probably remove the check here and just put "2022" since prefill is only called on new forms

2025-01-07 17:53 UTC, tommasina-va commented on app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
> +      if Flipper.enabled?(:disability_526_toxic_exposure_ipf,
I was trying to not step on Seth's toes with the remove BE toggle story, but sure, I can do that :)

2025-01-07 19:07 UTC, sethdarragile6 commented on app/models/form_profiles/va_526ez.rb
> +      started_form_version: Flipper.enabled?(:disability_526_toxic_exposure, user) ? '2022' : '2019',
y'all are making my future merge conflicts too easy! 😂
https://github.com/department-of-veterans-affairs/vets-api/pull/20043/files

2025-01-07 19:25 UTC, aurora-a-k-a-lightning approved these changes
seth informed me that his PR has the changes i requested
https://github.com/department-of-veterans-affairs/vets-api/pull/20043/files

2025-01-09 00:25 UTC, sethdarragile6 submitted a review, later dismissed

2025-01-09 15:40 UTC, LindseySaari submitted a review, later dismissed

2025-01-09 16:12 UTC, aurora-a-k-a-lightning approved these changes

2025-01-09 16:12 UTC, sethdarragile6 approved these changes

2025-01-10 15:20 UTC, tommasina-va commented
@LindseySaari Sorry, would you mind re-reviewing this one? Thanks!

2025-01-10 15:22 UTC, LindseySaari approved these changes

2025-01-10 15:22 UTC, merged