Add Commit Status Verification to deploy-template
department-of-veterans-affairs/vets-api pull request #20031
Opened 2024-12-26 17:37 UTC by rjohnson2011

## Summary

The workflow prevents deploying failed commits through these key steps:

In prepare-values job:

Gets AWS credentials
Uses GitHub API to check commit status
Fails early if commit status isn't "success"

The release job runs only if prepare-values succeeds since it has needs: [prepare-values]

This prevents the race condition where:

Commit A passes tests
Commit B merges quickly after
A's deployment picks up B's SHA
B fails tests but gets deployed

Now the workflow verifies B's status explicitly before allowing deployment.

## Related issue(s)

[Github Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96743)

2024-12-26 18:40 UTC, rmtolmach commented on .github/workflows/deploy-template.yml
>        - name: Configure AWS Credentials
This step was in the `release` section, but now it's in the `prepare-values` section. Was that intentional or

2024-12-26 18:40 UTC, rmtolmach commented on .github/workflows/deploy-template.yml
> +            | jq -r '.state')
The only check we care about passing is Code Checks. When I was on support, I saw `Build And Publish Preview Environment` fail a lot, but that one doesn't matter to us.

2024-12-26 18:50 UTC, RachalCassity commented
I found the error: [Build, Push, & Deploy](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/build.yml) action is rendering the incorrect image tag. I’m digging further. 
[@Ryan Johnson](https://oddball.slack.com/team/U01BS7YK9ML)
 The [${{ github.sha }}](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/build.yml#L55) is incorrect. We need to fix the incorrect github.sha issue. This pull request will not fix the issue.

2024-12-26 18:50 UTC, RachalCassity requested changes
Please fix the github.sha issue

2024-12-27 17:55 UTC, rjohnson2011 commented
> Please fix the github.sha issue

Made the changes discussed to `build.yml` and `deploy-template.yml`

2024-12-30 15:19 UTC, LindseySaari approved these changes
@rjohnson2011 Please place the before/after output in the PR description but otherwise looks good!

2024-12-30 16:15 UTC, merged