94111: 21P-530EZ Wire up flipper and new logic for email notification
department-of-veterans-affairs/vets-api pull request #20065
Opened 2024-12-31 21:22 UTC by balexandr

Add some [Flipper] logic to BenefitsIntakeJob to send a notification email for Burials only.

## Summary

- Update settings.yml with fake flipper name
- Add flipper with new method to BenefitsIntakeJob
- Update SubmissionStatusJob with same logic
- Clean up engine file

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#94111

2025-01-02 21:22 UTC, danlim715 requested changes
The `submission_status_job.rb` is a generic class so those changes should go in the burial specific handler, but looks good otherwise.

2025-01-02 21:22 UTC, danlim715 commented on lib/lighthouse/benefits_intake/sidekiq/submission_status_job.rb
Burial specific logic should be handled in `modules/burials/lib/benefits_intake/submission_handler.rb` which is the inheriting handler in the burial engine.

2025-01-03 22:29 UTC, danlim715 approved these changes

2025-01-06 14:26 UTC, LindseySaari approved these changes

2025-01-06 14:40 UTC, merged