13065 ApplicationController Concern Refactor
department-of-veterans-affairs/vets-api pull request #4914
Opened 2020-09-16 22:42 UTC by kreek

## Description of change
This PR is pre-work for the mobile auth PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/4898) (which includes these changes).

Moves the core vets-api `ApplicationController` logic into concerns so that they can be composed into the mobile `ApplicationController` (and any future controllers that don't use SAML auth). The lib `SentryLogging` module has a small refactor of duplicate code. The rest of the logic lives in four new concerns:
* `ExceptionHandling`: has the exception mapping and rails/sentry logging of the original errors
* `Headers`: has the`prepend_before_action` callback which sets the X-Git... headers
* `Instrumentation`: has the custom `append_info_to_payload` method
* `SentryControllerLogging`: the sentry logging that's specific to controllers

## Original issue(s)
department-of-veterans-affairs/va.gov-team#13065

## Things to know about this PR
* The mobile auth design doc is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/mobile-ssoe-design-doc/platform/engineering/design-docs/2020-08-12-mobile-ssoe-auth-design-doc.md)

2020-09-18 17:40 UTC, jholton approved these changes
Nice organizing!

2020-09-18 17:58 UTC, jjulian approved these changes

2020-09-18 20:17 UTC, erluti commented on app/controllers/application_controller.rb
move the above `require`s to the new concerns they belong with, please

2020-09-18 20:20 UTC, kfrz approved these changes
This is great!!! Very happy to see these changes. Looks good to me and looks like the specs are still passing. :+1: :zap: Thanks!

2020-09-18 20:37 UTC, erluti requested changes
I don't want this comment to be missed https://github.com/department-of-veterans-affairs/vets-api/pull/4914#discussion_r491170522

2020-09-21 13:29 UTC, erluti approved these changes
Thanks for keeping those `require`s!

2020-09-21 15:50 UTC, kreek commented
thanks for looking at this again @erluti, I'll merge this after the deploy today and test on staging

2020-09-21 19:01 UTC, merged