Add BIRLS columns to form526_submissions
department-of-veterans-affairs/vets-api pull request #5234
Opened 2020-11-06 03:50 UTC by edmangimelli

2020-11-06 15:59 UTC, annaswims requested changes
It looks like you didn't commit all changes in this file.  Specifically, I'm looking for the version number change.

`ActiveRecord::Schema.define(version: 2020_11_06_023750) do`

2020-11-06 16:58 UTC, edmangimelli commented
> It looks like you didn't commit all changes in schema.rb. Specifically, I'm looking for the version number change.
> 
> `ActiveRecord::Schema.define(version: 2020_11_06_023750) do`

thanks for catching that!

2020-11-09 14:51 UTC, annaswims approved these changes
LGTM

2020-11-09 14:51 UTC, annaswims commented on db/migrate/20201106023750_add_birls_columns_to_form526_submissions.rb
> +      comment: '*After* a SubmitForm526 Job fails, a lookup is done to see if the veteran has multiple ' \
❤️ Comments!

2020-11-09 20:45 UTC, ericboehs approved these changes

2020-11-10 16:37 UTC, merged