API-3828 Add status to notice of disagreement
department-of-veterans-affairs/vets-api pull request #5401
Opened 2020-11-27 16:08 UTC by ElleeB

## Description of change
Need to add status to notice of disagreements table
https://vajira.max.gov/browse/API-3828

## Things to know about this PR
Two migration files added

2020-11-27 17:42 UTC, charleystran requested changes
Can you move these migrations into modules/appeals_api/db/migrate?

2020-11-27 20:16 UTC, ElleeB commented on modules/appeals_api/bin/rails
> -ENGINE_PATH = File.expand_path('../lib/vba_documents/engine', __dir__)
Found this while working on this ticket. Seems incorrect. Please see my change and let me know.

2020-11-30 14:58 UTC, charleystran approved these changes

2020-11-30 14:58 UTC, charleystran approved these changes
LGTM

2020-11-30 15:10 UTC, merged