API-3264: Special Issues - 526 JSON Schema update (include schema inside of disability objects)
department-of-veterans-affairs/vets-api pull request #5504
Opened 2020-12-14 16:21 UTC by SlakrHakr

## Description of change
Ensure all valid special issues are allowed through the API

## Original issue(s)
https://vajira.max.gov/browse/API-3264

## Things to know about this PR
Specs for valid/invalid special issues through the API seem to already exist:
https://github.com/department-of-veterans-affairs/vets-api/blob/42b7769ffba861692eb5bdabfceb0b148c2bb52c/modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb#L127
https://github.com/department-of-veterans-affairs/vets-api/blob/42b7769ffba861692eb5bdabfceb0b148c2bb52c/modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb#L156

2020-12-16 15:35 UTC, bastosmichael requested changes
Do we have a list of what these all mean that we can attach either in PDF form with a link in the descriptions or something so that it's not at all confusing to the end consumer what these all mean?

2020-12-17 21:19 UTC, SlakrHakr commented
Human readable items have been swapped in and mapper between those and internal codes was added as well.

2020-12-17 22:22 UTC, SlakrHakr commented on app/swagger/swagger/schemas/form526/disability.rb
> +              'MST',
these are the special issues that are already published out to production

2020-12-17 22:23 UTC, SlakrHakr commented on modules/claims_api/lib/claims_api/special_issue_mapper.rb
> +      { name: 'MST', code: 'MST' },
these are the special issues that are already published out to production

2020-12-21 16:09 UTC, bastosmichael approved these changes
LGTM

2020-12-21 16:15 UTC, merged