Remove and add 'use on file' for address, phone, email
department-of-veterans-affairs/vets-api pull request #5545
Opened 2020-12-17 21:56 UTC by ElleeB

## Description of change
Veteran address, phone, and email should prompt intake specialist to use the Veteran's address on file

## Original issue(s)
address: https://vajira.max.gov/browse/API-4035
email: https://vajira.max.gov/browse/API-4036
phone: https://vajira.max.gov/browse/API-4037

## Testing
Tests and minimum expected pdf updated

2020-12-17 23:05 UTC, ElleeB commented
<img width="1163" alt="Screen Shot 2020-12-17 at 6 05 03 PM" src="https://user-images.githubusercontent.com/30485143/102554287-7bb82280-4092-11eb-98d3-18f5fa963949.png">

2020-12-18 18:59 UTC, cilestin requested changes
Surprised this didn't require an update to the minimum pdf as well. Does it not have an example email at least that should have changed from `a@a.com` to `use email on file`? 🤔

2020-12-18 18:59 UTC, cilestin commented on modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb
> -      expect(reader.pages.first.text).to include email
We should make sure the PDF has the "Use `X` on file" content

2020-12-18 20:14 UTC, cilestin approved these changes
LGTM 🎉

2020-12-18 20:15 UTC, merged