17772: STEM AD: TIMS Work
department-of-veterans-affairs/vets-api pull request #5644
Opened 2021-01-11 14:58 UTC by elder-joseph

## Description of change
As a developer, I need to create a new TIMS doc type and corresponding spool file to record a permanent record of the STEM automated decision.

## Original issue(s)
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17772

## Testing

2021-01-11 15:52 UTC, shawkey-daniel approved these changes
LGTM

2021-01-12 19:07 UTC, zurbergram requested changes
See schema for column names

2021-01-12 19:07 UTC, zurbergram commented on app/workers/education_form/forms/va10203.rb
> +      @education_stem_automated_decision&.decision_state == 'denied' ? '10203DNY' : 'V10203'
```suggestion
      @education_stem_automated_decision&.automated_decision_state == 'denied' ? '10203DNY' : 'V10203'
```

2021-01-12 19:07 UTC, zurbergram commented on app/workers/education_form/forms/va10203.rb
> +      @education_stem_automated_decision&.decision_state == 'denied' ? 'VA Form 22-10203DNY' : 'VA Form 22-10203'
```suggestion
      @education_stem_automated_decision&.automated_decision_state == 'denied' ? 'VA Form 22-10203DNY' : 'VA Form 22-10203'
```

2021-01-15 16:57 UTC, sonntag-adam approved these changes

2021-01-19 14:26 UTC, closed without merging