API-4292: Export claim IDs for flashes and special issues
department-of-veterans-affairs/vets-api pull request #5724
Opened 2021-01-20 16:06 UTC by SlakrHakr

## Description of change
Rake task for exporting established claims for a given datetime range. Primarily whether those claims contained any flashes or special issues.

## Original issue(s)
https://vajira.max.gov/browse/API-4292

## Things to know about this PR
Ran rake task locally.
Ran the logic within this rake task in production to get an initial report.

2021-01-21 21:48 UTC, bastosmichael requested changes
Test?

2021-01-21 23:31 UTC, SlakrHakr commented
> Test?

https://github.com/department-of-veterans-affairs/vets-api/pull/5724/commits/b8b2dec2ac4094d8b8997dc549850b821435a8c4
https://github.com/department-of-veterans-affairs/vets-api/pull/5724/commits/c1459a10203b1641c30fb08dfd39b4b8361fc0d4

2021-01-22 02:36 UTC, SlakrHakr commented on modules/claims_api/spec/lib/claims_api/power_of_attorney_pdf_constructor_spec.rb
> +require_relative '../../support/pdf_matcher'
i dont know why i had to change this... this file was suddenly unable to find this pdf_matcher support file for some reason...

2021-01-22 21:42 UTC, hinzed1127 approved these changes
lgtm 👍

2021-01-26 15:05 UTC, bastosmichael approved these changes

2021-01-26 15:12 UTC, merged