API-4589: Record not saving in sandbox after claim establishment through EVSS
department-of-veterans-affairs/vets-api pull request #5734
Opened 2021-01-21 15:39 UTC by SlakrHakr

## Description of change
After working through this, im not 100% sure why this is working correctly in production now, but it definitely is somehow.
When i run through the internals of the ClaimEstablisher job in sandbox it fails to save because of the `uniqueness` validation on the record's md5. That md5 will always be the same at that point in the logic, because it is generated from the record's `auth_headers` and `form_data` which are unchanged at that point.

Even weirder is that calling `save` once more, after the initial save fails, succeeds (all in sandbox i should reiterate). I'm not sure why this is the case...

Hopefully this change makes overall sense for this logic (and also seems to resolve sandbox as a nice side-effect). It essentially only validates the uniqueness of the md5 on create, not update. 

## Original issue(s)
https://vajira.max.gov/browse/API-4589

## Things to know about this PR
Tested manually in sandbox environment.
Existing spec tests still pass.

2021-01-21 15:39 UTC, SlakrHakr commented on modules/claims_api/app/workers/claims_api/claim_establisher.rb
> +      auto_claim.save!
I changed this so at least the background job would fail out at this point. Currently, in sandbox, this just returns false and moves on.

2021-01-21 21:46 UTC, bastosmichael requested changes
Can you include a test to test for and ensure failure?

2021-01-21 22:05 UTC, SlakrHakr commented
> Can you include a test to test for and ensure failure?

Done here: https://github.com/department-of-veterans-affairs/vets-api/pull/5734/commits/d35db39ab108ccfec75b0b67be2c612538d74104

2021-01-22 21:37 UTC, hinzed1127 approved these changes

2021-01-26 15:05 UTC, bastosmichael approved these changes

2021-01-26 15:10 UTC, merged