Refactor zipCode5 for zeros if homeless and no address
department-of-veterans-affairs/vets-api pull request #5916
Opened 2021-02-11 20:19 UTC by ElleeB

## Description of change
If a veteran is experiencing homelessness, including an address is optional. However, CentralMail requires a 5-digit zip code from our request. We've refactored so that `zipCode5 => 00000` is sent via the request in cases of homelessness with no address. 

## Original issue(s)
https://vajira.max.gov/browse/API-4832

## Testing
`zipCode5 formatting` tested in model spec
`address presence if not experiencing homelessness` tested in controller spec

2021-02-11 20:20 UTC, ElleeB commented on lib/common/exceptions/detailed_schema_errors.rb
> +        i18n_interpolated :schema
saw it had to do it

2021-02-11 20:20 UTC, ElleeB commented on modules/appeals_api/config/schemas/10182.json
> +
because all of the others have a double space between them

2021-02-12 03:14 UTC, cilestin requested changes

2021-02-12 03:14 UTC, cilestin commented on modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
> +      address ? address['zipCode5'] : '00000'
```
veteran_contact_info&.dig('address', 'zipCode5') || '00000'
```
seems cleaner to me

2021-02-12 14:50 UTC, ElleeB commented on modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
> +      address ? address['zipCode5'] : '00000'
yes

2021-02-17 19:30 UTC, cilestin approved these changes

2021-02-18 15:31 UTC, merged