Tud add services
department-of-veterans-affairs/vets-api pull request #6020
Opened 2021-02-25 18:10 UTC by jimiray

# Description of change

Fetch and Store a TUD Account: 
- services 
- account_uuid 
- 
## Original issue(s)

[Query & add MPI data to TUD account resource](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18967)

## Things to know about this PR

2021-02-25 19:55 UTC, bramleyjl requested changes

2021-02-25 19:55 UTC, bramleyjl commented on modules/test_user_dashboard/spec/services/create_test_user_account_spec.rb
>    end
The test failure looks like it's happening here, I think we need to change this to be expecting the CreateTestUserAccount service and not a `TudAccount` instance?

2021-02-26 01:42 UTC, ericboehs approved these changes
For the seed, you could amend the Dangerfile to allow db/seeds dirs.

2021-02-26 01:42 UTC, ericboehs commented on modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb
> +                                       loa: { lowest: 1, highest: 3 })
As a fellow writer of beautiful code, you can do this and rubocop will be happy:

```suggestion
        identity = UserIdentity.create(
          uuid: account_uuid,
          email: email,
          first_name: first_name,
          last_name: last_name,
          gender: gender,
          birth_date: birth_date.to_s(:iso_8601),
          ssn: ssn,
          loa: { lowest: 1, highest: 3 }
        )
```

2021-03-02 21:34 UTC, bramleyjl approved these changes
LGTM

2021-03-08 17:35 UTC, merged