remove form526_confirmation_email and form526_confirmation_email_copy feature toggles
department-of-veterans-affairs/vets-api pull request #6583
Opened 2021-04-14 19:12 UTC by saman-moshafi-va

## Description of change
form526_confirmation_email and form526_confirmation_email_copy feature toggles are obsolete since they have been enabled in production for a few months. This PR removes form526_confirmation_email and form526_confirmation_email_copy feature toggles.

## Original issue(s)
department-of-veterans-affairs/notification-api#248

## Things to know about this PR

The unit tests all run.

2021-04-14 20:20 UTC, ffafara-tw requested changes

2021-04-14 20:20 UTC, ffafara-tw commented on config/features.yml
> -  form526_confirmation_email_show_copy:
This has to wait until changes in vets-website are deployed to prod.

2021-04-14 20:20 UTC, ffafara-tw commented on spec/models/form526_submission_spec.rb
>        it 'returns one job triggered when feature flag enabled' do
Rename the test?

2021-04-20 20:03 UTC, saman-moshafi-va commented on spec/models/form526_submission_spec.rb
>        it 'returns one job triggered when feature flag enabled' do
Done

2021-04-20 20:39 UTC, LindseySaari approved these changes

2021-04-21 14:32 UTC, ffafara-tw approved these changes

2021-04-21 14:39 UTC, merged