Adds covid_vaccine_scheduling_frontend
department-of-veterans-affairs/vets-api pull request #6859
Opened 2021-05-12 18:28 UTC by mpelzsherman

## Description of change
Adds a feature flag that will be used to toggle the availability of covid-19 vaccine scheduling links in the facility locator frontend. Also sorts the feature flags using http://yaml-sorter.herokuapp.com/.

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22139

2021-05-12 18:43 UTC, mpelzsherman commented
I’m willing to go through and change the descriptions back to using `>` if desired.

OTOH it’s nice to be able to run the sort again as needed.

I can also make the sorting a separate PR if folks insist.

2021-05-13 12:34 UTC, thilton-oddball requested changes
The addition of the feature flag looks good but I'd request that you remove all of the quotes and line feeds that were added. Though there are no hard and fast rules, quotes seem to generally not be used unless needed in YAML files. The quotes and line feeds that were added don't seem to be necessary and introduce inconsistency to the file as they were  applied to some but not all entries.

2021-05-13 15:25 UTC, mpelzsherman commented
The quotes have been removed.

2021-05-13 16:19 UTC, thilton-oddball requested changes
There are a small handful of entries where a trailing quote mark was missed. If these can be cleaned up then I think we're good.

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: Hide ppms community care searches"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: Front End Flag to suppress the ability to search for pharmacies"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: Use an hexdigest for the ID on PPMS Place of Service Calls"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: force the legacy urgent care path to use the new POS locator"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: Use predictive location search in the Facility Locator UI"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: A fast and dirty way to get the operating status from lighthouse"
Trailing quote mark missed

2021-05-13 16:19 UTC, thilton-oddball commented on config/features.yml
> +    description: Display new field operationalHoursSpecialInstructions for VA facilities"
Trailing quote mark missed

2021-05-13 16:49 UTC, mpelzsherman commented
Sorry about those trailing quotes. I think I've got them all.

Those were introduced by the sorting tool I used. Hopefully folks will keep the keys sorted going forward so we won't have this issue again.

2021-05-13 17:33 UTC, thilton-oddball approved these changes
This all looks good now!

2021-05-13 18:08 UTC, merged