Update security properties for claims v1 swagger
department-of-veterans-affairs/vets-api pull request #7233
Opened 2021-06-15 01:59 UTC by hinzed1127

## Description of change

This updates the [security definitions](https://swagger.io/docs/specification/2-0/authentication/) in claims v1 swagger to properly reflect that it's using OAuth for authentication.

## Original issue(s)
https://vajira.max.gov/browse/API-7860

## Things to know about this PR

In and of itself, this doesn't give us anything extra within swagger ui. The developer portal doesn't currently have the OAuth flow implemented from swagger ui, and even when using https://editor.swagger.io/, I don't think that it'll redirect properly.

<img width="451" alt="Screen Shot 2021-06-14 at 8 07 07 PM" src="https://user-images.githubusercontent.com/13280995/121981256-f36dbe00-cd52-11eb-8541-df049bbc021d.png">

This will require dev work on the portal and registering the portal as a valid OAuth consumer for in-browser requests to work properly. TBD if that's a route us or other teams are interested in pursuing, but this lays the groundwork for that.

2021-06-15 02:01 UTC, hinzed1127 commented on modules/claims_api/app/swagger/claims_api/v1/swagger.json
> +      "sandboxOauth": {
This name is arbitrary and can be updated to something different if desired

2021-06-15 12:25 UTC, LindseySaari approved these changes

2021-06-15 16:22 UTC, SlakrHakr requested changes
it breaks the curl generator on the dev portal :(
i thought i had tried everything but apparently i missed the: bearer token + curl generator feature
not sure how we can have these live side by side but this needs to be investigated, what is the portal needing for that bearer token + curl generator to function properly?

2021-06-16 16:22 UTC, SlakrHakr approved these changes

2021-06-16 16:40 UTC, merged