Update claims OAuth scopes for sandbox
department-of-veterans-affairs/vets-api pull request #7250
Opened 2021-06-16 21:37 UTC by hinzed1127

## Description of change

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR

2021-06-17 12:57 UTC, LindseySaari approved these changes

2021-06-17 12:57 UTC, LindseySaari submitted a review, later dismissed
Looks like a flapping spec is failing, but these changes look good!

2021-06-22 14:26 UTC, LindseySaari approved these changes

2021-06-29 21:53 UTC, SlakrHakr requested changes
This shouldn't be needed anymore.
We were finally able to prove that the existing scopes are all that is necessary for this to operate.
https://sandbox-api.va.gov/services/claims/docs/swagger/index.html

2021-07-12 17:36 UTC, closed without merging