Toggle CG PDF facility data source by feature flag
department-of-veterans-affairs/vets-api pull request #7429
Opened 2021-07-13 21:50 UTC by dnalbach

## Description of change
This PR adds a facility client reference specifically useful for retrieving a list of Caregiver facilities, and adds a feature toggle in the Caregiver PDF generation to allow live API fetch of the facilities and names rather than using the current JSON Schema. 

## Original issue(s)
department-of-veterans-affairs/va.gov-team#26247

## Things to know about this PR
This uses the feature flag `ezcg_use_facility_api` which is defaulted to off currently.  Existing tests were refactored and modified in Rspec to verify in separate tests that the new code branch works with the feature flag off or on. The resulting PDF file is verified to be the same, regardless of whether it sources the facility list from the JSON schema or the Facility client.

2021-07-19 22:13 UTC, dnalbach commented
I got a lot of random test failures over the course of this PR, and had to rerun the PR check jobs a lot of times to tell which test failures were real and which ones were flaky. After my final code push today, I ran the PR check jobs three separate times with three completely different results each time. The first and second runs each failed completely different tests, while the third and final run passed everything, with no code changes between the three runs, so I am submitting it for review and merge.

2021-07-20 14:00 UTC, rileyanderson requested changes

2021-07-20 14:00 UTC, rileyanderson commented on lib/pcafc/facilities.rb
> +    STATION_NUMBERS = %w[vha_402 vha_405 vha_436 vha_437 vha_438 vha_442 vha_459 vha_460 vha_463 vha_501 vha_502 vha_503 vha_504 vha_506 vha_508 vha_509 vha_512 vha_515 vha_516 vha_517 vha_518 vha_51
Can you put these on multiple lines for readability? Something like this should work 

```ruby
%w[vha_402 vha_405 vha_436 vha_437 vha_438 vha_442
   vha_459 vha_460 vha_463 vha_501 vha_502 vha_503
   ....]

2021-07-20 17:58 UTC, rileyanderson commented
@dnalbach Looks good. You'll need to rebase with master to fix the brakeman failure

2021-07-20 21:50 UTC, rileyanderson approved these changes

2021-07-20 22:10 UTC, merged