Access tokens in openid controller are hashed
department-of-veterans-affairs/vets-api pull request #7561
Opened 2021-08-02 17:20 UTC by lukemarkwordtlibertyits

## Description of change
Access tokens in the openid_application controller will be hashed

## Original issue(s)
https://vajira.max.gov/browse/API-6281

2021-08-04 20:31 UTC, dbrown-va requested changes
There is one other session look up modification that is needed in the Veteran Verification module surrounding the mock vs real emis support.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran_verification/app/controllers/veteran_verification/application_controller.rb#L18

2021-08-05 14:21 UTC, beaugrantham-va commented
Can the hashing implementation be moved into a method?

```
def hash_token(token) ...
```

This will let us change the implementation (e.g., SHA-2 -> SHA-3) without having to update it in so many places, risking missing something.

2021-08-05 20:26 UTC, dbrown-va commented on modules/veteran_verification/app/controllers/veteran_verification/application_controller.rb
> +      @session = Session.find(Digest::SHA256.hexdigest(token.to_s))
This should have similar `@session = Session.find(token) if @session.nil?` fallback logic, right?

2021-08-06 15:20 UTC, dbrown-va approved these changes
Looks good.

2021-08-06 16:13 UTC, merged