adds authn_context validation check for inbound SSOe logins [#342]
department-of-veterans-affairs/vets-api pull request #8830
Opened 2022-01-07 22:07 UTC by bramleyjl

## Description of change

This change moves adds a validation for the `authn` parameter on inbound SSOe logins, raising an error if the authn_context does not match any of the contexts listed in the AUTHN_CONTEXTS object in `lib/saml/user.rb`

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#0000
](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team-sensitive/342)

## Things to know about this PR

Unit specs updated to test the auth_context validation, modified inbound SSOe from AccessVA performed.

2022-01-09 21:14 UTC, ericboehs commented on app/controllers/concerns/authentication_and_sso_concerns.rb
> +      SAML::User::AUTHN_CONTEXTS.keys.include?(authn)
Nit: Using multiple lines for an inline conditional feels weird. I think I'd break it out to the block syntax or perhaps invert the logic via `if ...exclude?` to keep it on one line.

2022-01-09 21:15 UTC, ericboehs approved these changes

2022-01-10 22:19 UTC, bosawt requested changes
Tested with idme and logingov, both had successful auth! 

I recommend the tiny change Eric recommended as well, just a code clarity accommodation. Otherwise, looks great!

2022-01-14 18:11 UTC, bosawt approved these changes
Looks good!

2022-01-14 23:27 UTC, ericboehs approved these changes

2022-01-18 19:14 UTC, merged