AL 32455 document upload
department-of-veterans-affairs/vets-api pull request #8979
Opened 2022-01-28 18:13 UTC by alsleaders

## Description of change
This change adds the ability to upload supporting documents to an in-progress 28-1880 file so they can be retrieved when the entire form is submitted to LGY

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#32455] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/32455)

## Things to know about this PR

2022-01-28 18:16 UTC, alsleaders commented
This is in draft because all the tests pass but I have not been able to test this locally yet.

2022-01-31 17:50 UTC, rileyanderson submitted a review, later dismissed

2022-02-03 17:33 UTC, alsleaders commented
The code and specs for this change are finished.  I have put the PR back into draft until I can log in locally (which is failing because of Id.me) and check that the document upload is successfully.

2022-02-08 04:46 UTC, alsleaders commented
Using user 71 I was able to log into my RI and see a pending application and upload a document, so the upload is successful.  I'm making a note on the PUT to LGY to make sure that when the entire form is submitted that we make sure the supporting documents are sent as well.

2022-02-08 20:16 UTC, thilton-oddball requested changes
One change needed so Rubocop won't be rolled back but otherwise looks good.

2022-02-08 20:16 UTC, thilton-oddball commented on Gemfile.lock
> +    rubocop (1.25.0)
We don't want to roll this back.

2022-02-08 21:32 UTC, alsleaders commented on Gemfile.lock
> +    rubocop (1.25.0)
Thanks Travis for catching that!

2022-02-09 15:48 UTC, thilton-oddball approved these changes

2022-02-09 16:47 UTC, merged