updates for backend flag on vets inbox
department-of-veterans-affairs/vets-api pull request #9077
Opened 2022-02-09 18:39 UTC by diondredroidios

## Description of change

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Things to know about this PR

2022-02-09 18:50 UTC, nathanielbuck requested changes

2022-02-09 18:50 UTC, nathanielbuck commented on Gemfile.lock
>    slack-notify
I don't think you meant to commit this file. Please revert these changes.

2022-02-09 19:50 UTC, nathanielbuck commented
You removed Gemfile.lock entirely, which isn't right either. You should restore it to its unmodified state. So, it shouldn't show up in the diff at all.

2022-02-09 22:09 UTC, nathanielbuck submitted a review, later dismissed

2022-02-21 16:46 UTC, LindseySaari approved these changes

2022-02-23 17:13 UTC, merged