API-12658 Notice of Disagreement V2 mvp data and structure
department-of-veterans-affairs/vets-api pull request #9155
Opened 2022-02-17 18:20 UTC by ElleeB

Adds for V2:
`form_data`
`form_data_spec`
v2 specific methods on nod model

Changes:
`veteran_representative` method name on nod model to `representative`
this change required a refactor to a v1 `form_data` method, but has no external impact

2022-02-17 18:23 UTC, ElleeB commented on modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
> -    def extension_request?
moved these methods up in the file

2022-02-17 18:23 UTC, ElleeB commented on modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
> -    def veteran_representative
modified v1 form_data to use `representative`

2022-02-17 19:14 UTC, cilestin requested changes
Lookin' pretty good! Only see one thing in my quick scan of it. Will give it a deeper look when I have more time to spare.

2022-02-17 19:18 UTC, ElleeB commented on modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
> +    def representative
Ah! Nice. I'll update it.

2022-02-21 21:44 UTC, cilestin approved these changes
LGTM!

2022-02-22 19:47 UTC, cilestin approved these changes

2022-02-22 19:49 UTC, merged