API-14203 charactervalidation expansion
department-of-veterans-affairs/vets-api pull request #9372
Opened 2022-03-16 00:28 UTC by cilestin

## Description of change
Removes the CharacterValidation controller concern and instead accepts any characters in the request, and delegates character encoding normalization as close to the problem as possible - the PDF generation.

## Original issue(s)
https://vajira.max.gov/browse/API-14203

## Things to know about this PR
* Adds `attr_readonly` to all appeal models to ensure we cannot override any data that might be modified during pdf generation
* Cleans up some files that were not used (10182 character fixtures)
* Removes character encoding section of the dev documentation

2022-03-16 19:23 UTC, ElleeB commented on modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb
> +            generated_pdf = PDF::Reader.new(path)
I wonder if naming this something different would help differentiate between the generated_pdf that we compare with expected_pdf. It seems like this plays a different role.

2022-03-16 19:23 UTC, ElleeB commented on modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb
> +            generated_pdf = PDF::Reader.new(path)
Same as above.

2022-03-16 19:27 UTC, ElleeB reviewed
Love this! I have one wondering about naming in the comments :)

2022-03-16 19:28 UTC, ElleeB requested changes
I have one wondering about naming in the comments :)

2022-03-16 20:22 UTC, stiehlrod approved these changes
LGTM

2022-03-17 17:25 UTC, ElleeB approved these changes
Looks good!!

2022-03-17 20:53 UTC, merged