Api 15056 birth past validation
department-of-veterans-affairs/vets-api pull request #9625
Opened 2022-04-13 20:58 UTC by stiehlrod

## Description of change
Adds `#birth_date_is_in_the_past` and `claimant_birth_date_is_in_the_past` validations.

## Original issue(s)
[API-15056](https://vajira.max.gov/browse/API-15056)

2022-04-13 21:16 UTC, ElleeB commented on modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
> +  context 'birth date isn\'t in the past' do
Let's update this to 'Veteran birth date...' since we now have claimant as well :)

2022-04-13 21:23 UTC, ElleeB approved these changes

2022-04-13 21:24 UTC, cilestin requested changes

2022-04-13 21:24 UTC, cilestin commented on modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
> +  context 'birth date isn\'t in the past' do
I agree with @ElleeB - let's match this wording with the text you added for claimant: "veteran birth date is in the future"

2022-04-13 21:25 UTC, ElleeB commented
I'm going to make a ticket for streamlining the wording of the tests. It's in multiple places where we have to add clarity for veteran and also streamline `is not in the past` vs `is in the future`

2022-04-13 21:37 UTC, cilestin approved these changes

2022-04-13 21:37 UTC, ElleeB commented on modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
> +  context 'Veteran birth date is not in the future' do
`Veteran birth date is in the future`

2022-04-13 21:38 UTC, ElleeB commented on modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
> +    it 'using a birth date /not/ in the past creates an invalid record' do
This can be shortened to `creates an invalid record` since the context takes care of the first part of the statement

2022-04-13 21:40 UTC, ElleeB commented on modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
> +    context 'claimant birth date is not in the future' do
I think we should add `when` to the start of this statement

2022-04-14 16:01 UTC, ElleeB approved these changes

2022-04-14 16:02 UTC, merged